import assert from 'node:assert/strict';
// Test the production service with deterministic media/inference adapters.
// Real Kokoro, IndexedDB persistence, and playback are verified separately in the browser.
globalThis.Audio=class {constructor(){this.paused=true;this.volume=1;this.muted=false;this.currentTime=0;}pause(){this.paused=true;}async play(){this.paused=false;this.onplaying?.();}};
let running=0,maxRunning=0;const order=[];
globalThis.Worker=class {
  postMessage(data){order.push(data.text);running++;maxRunning=Math.max(maxRunning,running);setTimeout(()=>{
    running--;
    this.onmessage({data:data.text==='FAIL'?{type:'error',message:'Offline test'}:{type:'audio',samples:new Float32Array([.1,.2,-.1,.3]),sampleRate:24000,device:'webgpu',rms:.2,peak:.3,elapsed:.01}});
  },20);}
  terminate(){}
};
const store=new Map([['recallflow_speech_engine','kokoro'],['recallflow_voice_default_v2','1']]);
globalThis.localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const {audioCache}=await import('./src/audio-cache.js');
const {KokoroVoice,speechKey,speakable}=await import('./src/kokoro-service.js');
const disk=new Map();
audioCache.get=async key=>disk.get(key);
audioCache.put=async entry=>disk.set(entry.key,entry);
audioCache.remove=async key=>disk.delete(key);
audioCache.deleteQuestion=async id=>{for(const [key,entry]of disk)if(entry.questionId===id)disk.delete(key);};
const options={questionId:'q1',role:'question',voice:'af_heart',speed:1};
const service=new KokoroVoice();
const a=service.speak('Tokyo?',options),b=service.speak('Tokyo?',options);
assert.equal(a,b,'rapid taps share the exact request');await a;
assert.equal(service.inferences,1);assert.equal(disk.size,1);assert.equal(service.state.evidence.cacheHit,false);
await service.speak('Tokyo?',options);assert.equal(service.inferences,1);assert.equal(service.state.evidence.cacheHit,true);
const reloaded=new KokoroVoice();await reloaded.speak('Tokyo?',options);
assert.equal(reloaded.inferences,0);assert.equal(reloaded.state.evidence.cacheSource,'IndexedDB');assert.equal(reloaded.worker,undefined);
for(const changed of [{voice:'am_michael'},{speed:.9},{role:'answer'},{questionId:'q2'}])await service.speak('Tokyo?',{...options,...changed});
await service.speak('Name Tokyo?',options);assert.equal(service.inferences,6);
await service.speak('Tokyo?',options);assert.equal(service.inferences,6,'switching back retains previous voice audio');
assert.notEqual(speechKey('Tokyo?',options),speechKey('Tokyo?',{...options,backend:'wasm'}));
assert.notEqual(speechKey('Fill ____',options),speechKey('Fill ____',{...options,spokenText:'Fill the gap'}));
assert.equal(speechKey('____',options),speechKey('____',{...options,spokenText:'blank'}),'underscore blanks are spoken as "blank"');
assert.equal(speakable('Paris is the ____ of ___.'),'Paris is the blank of blank.');
const pending=service.speak('Canceled request',options);service.stop();await pending;
assert.equal(service.state.phase,'idle');assert.equal(service.audio.paused,true,'canceled generation never auto-plays');
const first=service.speak('Queued first',options),second=service.speak('Queued second',options);await Promise.all([first,second]);
assert.equal(maxRunning,1,'different requests serialize inference');assert.equal(service.state.evidence.text,'Queued second');
const damagedKey=speechKey('Damaged?',{...options,backend:'auto'});
disk.set(damagedKey,{key:damagedKey,questionId:'q1',blob:new Blob(['invalid']),evidence:{rms:.1,durationSeconds:1}});
await reloaded.speak('Damaged?',options);assert.equal(reloaded.inferences,1);assert.equal(reloaded.state.evidence.cacheHit,false);
await service.deleteQuestion('q1');assert.ok([...disk.values()].every(entry=>entry.questionId!=='q1'));
const deleting=service.speak('Delete during generation',{...options,questionId:'delete-race'});
await new Promise(resolve=>setTimeout(resolve,5));await service.deleteQuestion('delete-race');await deleting;
assert.ok([...disk.values()].every(entry=>entry.questionId!=='delete-race'));
await service.speak('FAIL',options);assert.equal(service.state.phase,'error');assert.match(service.state.status,/Offline test/);
audioCache.put=async()=>{throw new Error('Quota exceeded');};
await service.speak('Storage full?',options);assert.equal(service.state.phase,'playing');assert.match(service.state.evidence.cacheWarning,/Quota/);
const count=service.inferences;await service.speak('Storage full?',options);assert.equal(service.inferences,count,'memory cache still works when persistence fails');
audioCache.clear=async()=>disk.clear();
await service.clearCache();assert.equal(disk.size,0);assert.equal(service.memory.size,0);assert.equal(service.state.evidence,null);assert.equal(service.audio.paused,true);
assert.equal(service.audio.src,'','clearing releases the previously loaded generated clip');assert.equal(service.url,null);
audioCache.put=async entry=>disk.set(entry.key,entry);
const clearDuringGeneration=service.speak('Clear while generating',options);
const cleared=service.clearCache();await Promise.all([clearDuringGeneration,cleared]);assert.equal(disk.size,0);assert.equal(service.memory.size,0);assert.equal(service.audio.paused,true);
console.log('PASS: request deduplication, serialization, persistence reuse, keys, edit/voice/speed isolation, cancellation, corruption, deletion races, and storage/generation failures.');

const preparedService=new KokoroVoice();
const prepared=await preparedService.prepare('Prepared question?',{...options,questionId:'prepared-editor'});
assert.equal(prepared.cacheHit,false);
assert.equal(preparedService.audio.paused,true,'preparing question voice never autoplays');
await preparedService.prepare('Prepared question?',{...options,questionId:'prepared-editor'});
assert.equal(preparedService.inferences,1,'saving the same question reuses audio');
await preparedService.speak('Prepared question?',{...options,questionId:'prepared-editor'});
assert.equal(preparedService.state.evidence.cacheHit,true,'speaker reuses prepared editor audio');
assert.equal(preparedService.inferences,1);
console.log('PASS: editor audio preparation, no autoplay, repeated-save reuse, and speaker cache reuse.');

const prefs=new Map([['recallflow_speech_engine','kokoro'],['recallflow_voice_default_v2','1']]);
globalThis.localStorage={getItem:key=>prefs.has(key)?prefs.get(key):null,setItem:(key,value)=>prefs.set(key,String(value)),removeItem:key=>prefs.delete(key)};
const tick=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const queued=new KokoroVoice();
queued.prefetch([{questionId:'p1',role:'question',text:'Prefetch A'}]);await tick(40);
assert.equal(queued.inferences,0,'prefetch waits until Kokoro has been used once');
prefs.set('recallflow_kokoro_ready','1');order.length=0;
queued.prefetch([{questionId:'p1',role:'question',text:'Prefetch A'},{questionId:'p1',role:'answer',text:'Prefetch B'},{questionId:'p2',role:'question',text:'Prefetch C'}]);
await tick(5);await queued.speak('User tap',{questionId:'u1',role:'question'});
assert.deepEqual(order.slice(0,2),['Prefetch A','User tap'],'a tap runs before queued background preparation');
assert.equal(queued.audio.paused,false,'the tapped clip plays');
await Promise.allSettled([...queued.requests.values()]);
assert.deepEqual(order,['Prefetch A','User tap','Prefetch B','Prefetch C']);
order.length=0;
queued.prefetch([{questionId:'p3',role:'question',text:'Next D'},{questionId:'p3',role:'answer',text:'Next E'},{questionId:'p4',role:'question',text:'Next F'}]);
await tick(5);await queued.speak('Next F',{questionId:'p4',role:'question'});
assert.deepEqual(order.slice(0,2),['Next D','Next F'],'tapping a pending prefetched clip promotes it');
await Promise.allSettled([...queued.requests.values()]);
const before=queued.inferences;order.length=0;
queued.prefetch([{questionId:'p5',role:'question',text:'Stale G'},{questionId:'p5',role:'answer',text:'Stale H'}]);
await tick(5);queued.prefetch([{questionId:'p6',role:'question',text:'Fresh I'}]);
await tick(5);await Promise.allSettled([...queued.requests.values()]);
assert.deepEqual(order,['Stale G','Fresh I'],'moving to the next question cancels stale background work');
assert.equal(queued.inferences,before+2);
prefs.set('recallflow_speech_engine','system');
queued.prefetch([{questionId:'p7',role:'question',text:'Device engine'}]);await tick(40);
assert.equal(queued.inferences,before+2,'device voice never loads Kokoro');
assert.deepEqual(await queued.prepare('Device engine',{questionId:'p7',role:'question'}),{skipped:true});
delete globalThis.localStorage;
console.log('PASS: tap priority over prefetch, promotion of pending clips, stale prefetch cancellation and engine gating.');
