import React,{useState,useEffect,useRef} from 'react';
import {readSetups,writeSetups} from '../quiz-setups.js';
import {Bookmark,Check,SlidersHorizontal,Shuffle,Save,Plus,Upload,Smartphone,GripVertical,Lock,LockOpen,Eye,EyeOff,FileArchive} from 'lucide-react';
import {MatchingAnswer,ItemMedia,ItemZoom,ItemText} from './QuestionInteractions';
import {Button} from './components/Button';
import {questionTypes,validateQuestion,typeLabel} from '../question-types.js';
import {filterQuiz,analytics,validateBackup,restoreBackup} from '../learning-core.js';
import {seededShuffle} from '../question-variants.js';
import {openBackupFiles,readArchive,asBackup} from '../backup-archive.js';
import {restoreImages} from '../sync.js';
export function QuizBuilder({items,reports,defaults,onStart,onClose}:any){
 const initial={mode:'daily',count:defaults.count||0,subject:'',topic:'',types:[] as string[],shuffle:defaults.shuffle,focus:'all'};
 const [c,set]=useState(initial),[setups,setSetups]=useState(readSetups),[active,setActive]=useState(''),[name,setName]=useState(''),[status,setStatus]=useState('');
 const saved=setups.find(p=>p.id===active),dirty=!saved||name.trim()!==saved.name||JSON.stringify(c)!==JSON.stringify(saved.controls);
 const q=filterQuiz(items,reports,c),field=(key:string,value:any)=>{set({...c,[key]:value});setStatus('');};
 const subjects=[...new Set(items.map(x=>x.subject))].sort() as string[],topics=[...new Set(items.filter(x=>!c.subject||x.subject===c.subject).map(x=>x.topic))].sort() as string[];
 function load(p:any){set({...p.controls,types:[...p.controls.types]});setActive(p.id);setName(p.name);setStatus(`Loaded ${p.name}.`);}
 function save(){try{const preset={id:active||crypto.randomUUID(),name:name.trim(),controls:c};const next=writeSetups(active?setups.map(p=>p.id===active?preset:p):[...setups,preset]);setSetups(next);setActive(preset.id);setName(preset.name);setStatus(`Saved ${preset.name}.`);}catch(e:any){setStatus(e.message||'Could not save this setup.');}}
 return <div className="quiz-builder-v2">
 <section className="quiz-config-card"><div className="quiz-config-heading"><Bookmark size={19}/><div><h2>Saved setups</h2><p>Save your choices once. Load them whenever you need.</p></div></div>
 {setups.length?<div className="quiz-preset-list">{setups.map(p=><button key={p.id} aria-label={`Load ${p.name}`} aria-pressed={active===p.id} onClick={()=>load(p)}><Bookmark size={15}/><span><strong>{p.name}</strong><small>{p.controls.count||'All'} questions · {p.controls.mode==='all'?'All questions':p.controls.mode==='due'?'Due questions':'Daily'}{p.controls.subject?` · ${p.controls.subject}`:''}</small></span>{active===p.id&&<Check size={16}/>}</button>)}</div>:<p className="quiz-preset-empty">No saved setups yet. Choose your settings below and give them a name.</p>}
 <div className="quiz-save-preset"><label>Setup name<input maxLength={50} placeholder="e.g. Biology · quick recall" value={name} onChange={e=>{setName(e.target.value);setStatus('');}}/></label><Button disabled={!name.trim()||!dirty} onClick={save}><Save size={15}/>{active?'Save changes':'Save setup'}</Button></div>
 {active&&<div className="quiz-preset-actions"><span>{dirty?'Unsaved changes':'Saved setup loaded'}</span><button onClick={()=>{setActive('');setName('');setStatus('Name this copy to save a new setup.');}}><Plus size={13}/>Save as new</button><button disabled={!dirty} onClick={()=>saved&&load(saved)}>Reset changes</button></div>}
 <p className="quiz-save-status" role="status" aria-live="polite">{status}</p></section>
 <section className="quiz-config-card"><div className="quiz-config-heading"><SlidersHorizontal size={19}/><div><h2>Questions</h2><p>Choose the size and content of this session.</p></div></div>
 <div className="quiz-config-grid"><label>Quiz length<select value={c.count?'custom':'all'} onChange={e=>field('count',e.target.value==='all'?0:Math.min(10,Math.max(1,items.length)))}><option value="all">All matching questions</option><option value="custom">Choose a number</option></select></label>{!!c.count&&<label>Question count<input type="number" min={1} max={1000} value={c.count} onChange={e=>field('count',Math.min(1000,Math.max(1,Number(e.target.value)||1)))}/></label>}
 <label>Subject<select value={c.subject} onChange={e=>{set({...c,subject:e.target.value,topic:''});setStatus('');}}><option value="">All subjects</option>{c.subject&&!subjects.includes(c.subject)&&<option>{c.subject}</option>}{subjects.map(x=><option key={x}>{x}</option>)}</select></label><label>Topic<select value={c.topic} onChange={e=>field('topic',e.target.value)}><option value="">All topics</option>{c.topic&&!topics.includes(c.topic)&&<option>{c.topic}</option>}{topics.map(x=><option key={x}>{x}</option>)}</select></label></div>
 <details className="quiz-type-options"><summary>Question types <span>{c.types.length?`${c.types.length} selected`:'All types'}</span></summary><div className="quiz-type-chips">{questionTypes.map(([id,label])=><label key={id}><input type="checkbox" checked={c.types.includes(id)} onChange={e=>field('types',e.target.checked?[...c.types,id]:c.types.filter(x=>x!==id))}/><span>{label}</span></label>)}</div><small>No types selected includes all types.</small></details></section>
 <section className="quiz-config-card"><div className="quiz-config-heading"><Shuffle size={19}/><div><h2>Practice</h2><p>Choose what to review and how it appears.</p></div></div><div className="quiz-mode-options" role="group" aria-label="Review mode">{[['daily','Daily'],['due','Due'],['all','All questions']].map(([id,label])=><button key={id} aria-pressed={c.mode===id} onClick={()=>field('mode',id)}>{label}</button>)}</div><p className="quiz-mode-help">{c.mode==='daily'?'Today’s due questions, with your chosen filters.':c.mode==='due'?'Questions ready for their next review.':'Practice regardless of the next review date.'}</p><label>Practice focus<select value={c.focus} onChange={e=>field('focus',e.target.value)}><option value="all">Everything</option><option value="weak">Weak questions</option><option value="mistakes">Previous mistakes</option></select></label><label className="quiz-shuffle-toggle"><span><strong>Shuffle question order</strong><small>A fresh order each time you start.</small></span><input type="checkbox" checked={c.shuffle} onChange={e=>field('shuffle',e.target.checked)}/></label></section>
 <footer className="quiz-config-footer"><div><strong>{q.length} {q.length===1?'question':'questions'}</strong><p>{q.length?'Ready with your current choices.':'Nothing matches. Change the filters or review mode.'}</p></div><Button disabled={!q.length} onClick={()=>onStart(filterQuiz(items,reports,c),c.mode,c.types)}>Start quiz</Button></footer>
 </div>;
}
async function imageFile(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a PNG, JPEG or WebP image under 2 MB.');return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});}
export function ExtendedEditor({draft,setDraft}:any){const [error,setError]=useState('');async function upload(file:File,key?:string){try{const image=await imageFile(file);setDraft(d=>key?{...d,optionImages:{...d.optionImages,[key]:image}}:{...d,image});setError('');}catch(e:any){setError(e.message);}}return <div className="extended-editor">{['matching','ordering','cloze','fill_blank_options'].includes(draft.type)&&<label>{draft.type==='matching'?'Matching pairs — left | right, one pair per line':draft.type==='ordering'?'Sequence steps — correct order, one per line':'Blank answers — one per ___ marker, in order'}<textarea value={draft.structured||''} onChange={e=>setDraft(d=>({...d,structured:e.target.value}))}/></label>}<label>Accepted alternative answers — one per line<textarea value={draft.accepted||''} onChange={e=>setDraft(d=>({...d,accepted:e.target.value}))}/></label><label className="learning-check"><input type="checkbox" checked={draft.fuzzy!==false} onChange={e=>setDraft(d=>({...d,fuzzy:e.target.checked}))}/>Accept one-character typos in words of 5+ letters</label><label>Tags — comma separated<input value={draft.tags||''} onChange={e=>setDraft(d=>({...d,tags:e.target.value}))}/></label><label>Question image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>{draft.image&&<><img className="question-media" src={draft.image} alt="Question preview"/><Button variant="outline" onClick={()=>setDraft(d=>({...d,image:undefined}))}>Remove question image</Button></>}{['single_choice','multi_select'].includes(draft.type)&&draft.options.split('\n').filter(Boolean).map(choice=><label key={choice}>Image for {choice}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],choice)}/>{draft.optionImages?.[choice]&&<><img className="choice-media" src={draft.optionImages[choice]} alt={choice}/><button onClick={()=>setDraft(d=>({...d,optionImages:Object.fromEntries(Object.entries(d.optionImages).filter(([k])=>k!==choice))}))}>Remove image</button></>}</label>)}<p role="status">{error}</p></div>;}
// Steps can be dragged with a mouse right away; on touch screens a short press (or the grip) starts the drag so the page still scrolls.
function OrderingSteps({item,values,onChange,disabled}:any){
 const rows=useRef<(HTMLDivElement|null)[]>([]),list=useRef<HTMLDivElement>(null),info=useRef<any>(null);
 const [drag,setDrag]=useState<null|{from:number,to:number,dy:number}>(null);
 useEffect(()=>{const el=list.current;if(!el)return;const block=(e:TouchEvent)=>{if(info.current?.active)e.preventDefault();};el.addEventListener('touchmove',block,{passive:false});return()=>el.removeEventListener('touchmove',block);},[]);
 function move(from:number,to:number){if(from===to)return;const x=[...values];const [step]=x.splice(from,1);x.splice(to,0,step);onChange(x);}
 function activate(){const d=info.current;if(!d)return;d.active=true;try{d.el.setPointerCapture(d.pointerId);}catch{}navigator.vibrate?.(8);setDrag({from:d.i,to:d.i,dy:0});}
 function down(i:number,e:React.PointerEvent<HTMLDivElement>){
  if(disabled||e.button>0||values.length<2)return;const target=e.target as HTMLElement;const grip=!!target.closest('.sequence-grip');
  if(!grip&&target.closest('button,a,input'))return;
  const rects=rows.current.slice(0,values.length).map(r=>r!.getBoundingClientRect());
  info.current={i,startY:e.clientY,rects,gap:rects.length>1?Math.max(0,rects[1].top-rects[0].bottom):8,active:false,pointerId:e.pointerId,el:e.currentTarget,timer:0};
  if(e.pointerType!=='touch'||grip){e.preventDefault();activate();}else info.current.timer=window.setTimeout(activate,220);
 }
 function over(e:React.PointerEvent){const d=info.current;if(!d)return;const dy=e.clientY-d.startY;
  if(!d.active){if(Math.abs(dy)>8){clearTimeout(d.timer);info.current=null;}return;}
  const r=d.rects[d.i],center=r.top+r.height/2+dy;
  setDrag({from:d.i,to:d.rects.filter((x:DOMRect,j:number)=>j!==d.i&&x.top+x.height/2<center).length,dy});}
 function up(){const d=info.current;info.current=null;if(!d)return;clearTimeout(d.timer);if(d.active&&drag)move(drag.from,drag.to);setDrag(null);}
 function shift(j:number){if(!drag)return undefined;if(j===drag.from)return {transform:`translateY(${drag.dy}px)`,transition:'none'};const r=info.current?.rects,size=r?r[drag.from].height+info.current.gap:0;
  if(drag.from<drag.to&&j>drag.from&&j<=drag.to)return {transform:`translateY(${-size}px)`};if(drag.from>drag.to&&j>=drag.to&&j<drag.from)return {transform:`translateY(${size}px)`};return undefined;}
 return <div className="sequence-list" ref={list} data-dragging={drag?'':undefined}>{!disabled&&values.length>1&&<p className="sequence-hint">Drag the steps into order, or use the arrows.</p>}{values.map((step:string,i:number)=><div className="sequence-step" key={step} ref={el=>{rows.current[i]=el;}} style={shift(i)} data-lifted={drag?.from===i?'':undefined} data-state={disabled?(step===item.sequence[i]?'correct':'wrong'):undefined} onPointerDown={e=>down(i,e)} onPointerMove={over} onPointerUp={up} onPointerCancel={up} onContextMenu={e=>{if(info.current)e.preventDefault();}}>{!disabled&&<span className="sequence-grip" aria-hidden="true"><GripVertical size={18}/></span>}<span className="sequence-num" aria-hidden="true">{i+1}</span><span className="media-slot"><ItemMedia item={item} text={step}/><ItemZoom item={item} text={step}/></span><span className="sequence-text"><span className="visually-hidden">{i+1}. </span><ItemText item={item} text={step}/></span><button aria-label={`Move ${step} up`} disabled={disabled||i===0} onClick={()=>move(i,i-1)}>↑</button><button aria-label={`Move ${step} down`} disabled={disabled||i===values.length-1} onClick={()=>move(i,i+1)}>↓</button></div>)}</div>;
}
export function StructuredAnswer({item,value,onChange,disabled,onGrade}:any){if(item.type==='matching')return <MatchingAnswer key={item.id} item={item} value={value} onChange={onChange} disabled={disabled} onGrade={onGrade}/>;const values=value.length?value:item.type==='ordering'?seededShuffle(item.sequence,item.id+(item.shuffleSeed||'')):Array(item.type==='matching'?item.pairs.length:item.blanks.length).fill('');function change(i:number,v:string){const copy=[...values];copy[i]=v;onChange(copy);}return <div className="structured-answer">{item.type==='matching'?item.pairs.map((p,i)=><label key={p.left}>{p.left}<select aria-label={`Match ${p.left}`} disabled={disabled} value={values[i]||''} onChange={e=>change(i,e.target.value)}><option value="">Choose a match</option>{[...item.pairs].reverse().map(p=><option key={p.right}>{p.right}</option>)}</select></label>):item.type==='cloze'?item.blanks.map((_,i)=><label key={i}>Blank {i+1}<input aria-label={`Blank ${i+1}`} disabled={disabled} value={values[i]||''} onChange={e=>change(i,e.target.value)}/></label>):<OrderingSteps item={item} values={values} onChange={onChange} disabled={disabled}/>}{!disabled&&<Button disabled={values.some(x=>!x)} onClick={()=>onGrade(values)}>Check answer</Button>}</div>;}
export function AnalyticsPanel({reports}:any){const a=analytics(reports);return <section className="learning-panel"><h2>Learning insights</h2>{!a.total?<p>Finish a quiz to see your strengths and weaknesses.</p>:<>{Object.entries(a.groups).map(([key,groups]:any)=><div key={key}><h3>Accuracy by {key}</h3><div className="analytics-rows">{Object.entries(groups).sort(([,a]:any,[,b]:any)=>a.correct/a.total-b.correct/b.total).map(([name,s]:any)=><div key={name}><span>{key==='type'?typeLabel(name):name}</span><strong>{Math.round(s.correct/s.total*100)}%</strong><small>{s.total} attempts · {(s.seconds/s.total).toFixed(1)}s average</small><progress max={s.total} value={s.correct}/></div>)}</div></div>)}<h3>Accuracy trend</h3><div className="trend-bars">{a.trend.map(r=><div key={r.id} title={`${r.date}: ${r.accuracy}%`}><span>{r.accuracy}%</span><progress max="100" value={r.accuracy}/><small>{new Date(r.date).toLocaleDateString()}</small></div>)}</div><h3>Repeated mistakes</h3>{a.mistakes.filter(x=>x.count>1).slice(0,10).map(x=><p key={x.prompt}>{x.prompt} <strong>· {x.count} misses</strong></p>)}{!a.mistakes.some(x=>x.count>1)&&<p>No repeated mistakes yet.</p>}</>}</section>;}
export function BackupRestore(){
 const [text,setText]=useState(''),[fileName,setFileName]=useState(''),[data,setData]=useState<any>(null),[images,setImages]=useState<any[]>([]),[status,setStatus]=useState('');
 const [archive,setArchive]=useState<any>(null),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[passError,setPassError]=useState(''),[busy,setBusy]=useState('');
 const locked=archive?.locked&&!data,passwordInput=useRef<HTMLInputElement>(null);
 function reset(){setText('');setFileName('');setData(null);setImages([]);setStatus('');setArchive(null);setPassword('');setShowPassword(false);setPassError('');}
 function review(){try{setData(validateBackup(asBackup(JSON.parse(text)),validateQuestion));setImages([]);setStatus('');}catch(e:any){setData(null);setStatus(e.message);}}
 async function unlock(a:any,pw:string){setBusy(a.locked?'Unlocking…':'Opening backup…');try{const r=await readArchive(a,pw);setData(validateBackup(r.data,validateQuestion));setImages(r.images);setStatus('');setPassError('');}catch(e:any){if(e.wrongPassword){setPassError(e.message);setTimeout(()=>passwordInput.current?.select());}else setStatus(e.message);}finally{setBusy('');}}
 function submitPassword(){if(password&&!busy)unlock(archive,password);}
 async function choose(list:FileList|null){const files=[...(list||[])];if(!files.length)return;reset();setBusy('Opening backup…');try{const r=await openBackupFiles(files);setFileName(r.label);if(r.kind==='json'){setText(r.text);setBusy('');return;}setArchive(r);setBusy('');if(!r.locked)await unlock(r,'');}catch(e:any){setBusy('');setStatus(e.message);}}
 async function confirm(){try{await restoreImages(images);restoreBackup(data);location.reload();}catch(e:any){setStatus('Restore failed; original data was retained. '+e.message);}}
 return <section className="settings-panel"><div className="settings-heading"><span className="settings-icon"><Upload size={19}/></span><div><h2>Restore backup</h2><p>Replace everything with a saved backup.</p></div></div>
  <div className="settings-file-row"><label className="settings-file-button">{archive?<FileArchive size={16}/>:<Upload size={16}/>}<span>{fileName||'Choose backup file'}</span><input type="file" multiple aria-label="Choose backup file" onChange={e=>{choose(e.target.files);e.target.value='';}}/></label>{!archive&&<Button variant="outline" disabled={!text.trim()||!!busy} onClick={review}>Review backup</Button>}</div>
  {!fileName&&<small className="settings-hint">A .json or .zip backup. For a backup in parts (.001, .002…), choose all parts together.</small>}
  {busy&&!locked&&<p className="settings-hint" role="status">{busy}</p>}
  {locked&&<form className="restore-lock" onSubmit={e=>{e.preventDefault();submitPassword();}}>
   <div className="restore-lock-head"><span className="restore-lock-icon"><Lock size={18}/></span><div><strong>This backup is locked</strong><p>Enter the backup password to open it.</p></div></div>
   <div className="restore-lock-field" data-error={!!passError||undefined}><input ref={passwordInput} type={showPassword?'text':'password'} autoFocus onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();submitPassword();}}} autoComplete="off" spellCheck={false} placeholder="Backup password" aria-label="Backup password" aria-invalid={!!passError} aria-describedby={passError?'restore-pass-error':undefined} value={password} onChange={e=>{setPassword(e.target.value);setPassError('');}}/><button type="button" className="restore-lock-eye" aria-label={showPassword?'Hide password':'Show password'} aria-pressed={showPassword} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>
   {passError&&<p id="restore-pass-error" className="restore-lock-error" role="alert">{passError}</p>}
   <div className="settings-button-row"><Button type="submit" disabled={!password||!!busy}><LockOpen size={16}/>{busy||'Unlock'}</Button><Button variant="outline" onClick={reset}>Cancel</Button></div>
  </form>}
  {!archive&&<details className="settings-paste"><summary>Or paste backup JSON</summary><textarea aria-label="Backup JSON" value={text} onChange={e=>{setText(e.target.value);setFileName('');setData(null);setImages([]);}}/></details>}
  {data&&<div className="settings-confirm"><p>Replace with {data.questions.length} questions, {images.length?`${images.length} ${images.length===1?'picture':'pictures'}, `:''}{data.reports.length} {data.reports.length===1?'report':'reports'} and {data.streakDays.length} activity {data.streakDays.length===1?'day':'days'}?</p><Button onClick={confirm}>Confirm restore backup</Button><Button variant="outline" onClick={reset}>Cancel restore</Button></div>}
  {status&&<p className="settings-error" role="alert">{status}</p>}
 </section>;}
export function OfflineSettings(){const [ready,setReady]=useState(false),[install,setInstall]=useState<any>(null);useEffect(()=>{let active=true;const check=()=>{if(active)setReady(!!navigator.serviceWorker?.controller);};check();navigator.serviceWorker?.addEventListener('controllerchange',check);navigator.serviceWorker?.ready.then(check);const prompt=(e:any)=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',prompt);return()=>{active=false;navigator.serviceWorker?.removeEventListener('controllerchange',check);window.removeEventListener('beforeinstallprompt',prompt);};},[]);return <section className="settings-panel"><div className="settings-heading"><span className="settings-icon"><Smartphone size={19}/></span><div><h2>Install &amp; offline</h2><p>Study without a connection.</p></div><span className="settings-badge" data-ready={ready}>{ready?'Ready':'Preparing'}</span></div>{install?<Button onClick={async()=>{await install.prompt();setInstall(null);}}>Install RecallFlow</Button>:<small className="settings-hint">To install, use your browser’s “Add to Home Screen” or “Install app”.</small>}</section>;}
