import React,{useState,useRef} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,Check,Save,LoaderCircle,ImagePlus,Eye,Volume2,BookOpen} from 'lucide-react';
import {questionTypes,typeLabel} from '../question-types.js';
import {Button} from './components/Button';
import {SpeechButton} from './KokoroPanel';
const help:any={short_answer:'Ask a direct question and write the answer you expect.',fill_blank:'Use ___ where the missing answer belongs.',single_choice:'Add choices, then select the one correct answer.',flashcard:'Write the front of the card and the answer on the back.',true_false:'Write a statement and choose whether it is true or false.',multi_select:'Add choices and mark every correct answer.',numeric:'Set the expected number and how much variation to accept.',matching:'Each row is a pair. Learners will connect the two sides.',ordering:'Write the steps in their correct order. The quiz will mix them up.',cloze:'Use ___ for each gap, then enter its answer below.',fill_blank_options:'Create gaps with ___ and give learners a word bank.'};
function ImageUpload({label,image,onPick,onRemove}:any){
 const input=useRef<HTMLInputElement>(null),[loading,setLoading]=useState(false);
 return <div className="editor-image-upload"><div className={`editor-upload-preview ${image?'has-image':''}`}>
 {image?<img src={image} alt={`${label} preview`}/>:<><ImagePlus size={31}/><span>No image added</span></>}
 </div><div className="editor-upload-bottom"><div><strong>{label}</strong><small>PNG, JPEG or WebP · up to 2 MB</small></div><button type="button" className="editor-upload-choose" disabled={loading} aria-label={`${image?'Change':'Choose'} ${label.toLowerCase()}`} onClick={()=>input.current?.click()}>{loading?<LoaderCircle size={15} className="speech-spinner"/>:null}{loading?'Adding…':image?'Change image':'Choose image'}</button></div>
 {image&&<button type="button" className="editor-upload-remove" aria-label={`Remove ${label.toLowerCase()}`} disabled={loading} onClick={onRemove}><Trash2 size={14}/>Remove image</button>}
 <input ref={input} type="file" aria-label={`Upload ${label.toLowerCase()}`} accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file){setLoading(true);try{await onPick(file);}finally{setLoading(false);}}}}/>
 </div>;
}
export function QuestionEditor({draft,setDraft,onSave,onCancel,busy,status,saved,editing,prepareAudio,setPrepareAudio,onAnother}:any){
 const [preview,setPreview]=useState(false),[mediaError,setMediaError]=useState('');
 const field=(key:string,value:any)=>setDraft((d:any)=>({...d,[key]:value}));
 const lines=(key:string,min=0)=>{const rows=String(draft[key]||'').split('\n');while(rows.length<min)rows.push('');return rows;};
 const update=(key:string,i:number,value:string,min=0)=>{const rows=lines(key,min);rows[i]=value;field(key,rows.join('\n'));};
 const choices=lines('options',2),steps=lines('structured',2),blankCount=(draft.prompt.match(/_{2,}/g)||[]).length;
 const pairs=steps.map((line:string)=>{const [left='',...rest]=line.split('|');return [left,rest.join('|')];});
 const markChoice=(choice:string,on:boolean)=>{if(draft.type==='single_choice')field('answer',choice);else{const answers=lines('answer').filter(Boolean);field('answer',(on?[...new Set([...answers,choice])]:answers.filter((x:string)=>x!==choice)).join('\n'));}};
 function choiceChange(i:number,value:string){const old=choices[i],next=[...choices];next[i]=value;setDraft((d:any)=>({...d,options:next.join('\n'),answer:d.type==='single_choice'?(d.answer===old?value:d.answer):String(d.answer).split('\n').map((x:string)=>x===old?value:x).join('\n'),optionImages:old&&d.optionImages?.[old]?{...d.optionImages,[old]:undefined,[value]:d.optionImages[old]}:d.optionImages}));}
 function removeChoice(i:number){const old=choices[i];setDraft((d:any)=>({...d,options:choices.filter((_:string,j:number)=>j!==i).join('\n'),answer:d.type==='single_choice'?(d.answer===old?'':d.answer):String(d.answer).split('\n').filter((x:string)=>x!==old).join('\n'),optionImages:Object.fromEntries(Object.entries(d.optionImages||{}).filter(([k])=>k!==old&&d.optionImages[k]))}));}
 async function upload(file:File,key?:string){try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a PNG, JPEG or WebP image under 2 MB.');const image=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Could not read this image.'));r.readAsDataURL(file);});setDraft((d:any)=>key?{...d,optionImages:{...d.optionImages,[key]:image}}:{...d,image});setMediaError('');}catch(e:any){setMediaError(e.message);}}
 if(saved)return <section className="editor-success" role="status"><span className="editor-success-icon"><Check size={30}/></span><h2>{editing?'Question updated':'Question created'}</h2><p>{status}</p><div className="editor-saved-question"><small>{typeLabel(saved.type)}</small><strong>{saved.prompt}</strong><SpeechButton questionId={saved.id} text={saved.prompt} spokenText={saved.type==='fill_blank'?saved.prompt.replace(/_{2,}/g,'blank'):undefined} label="Play saved question audio"/></div><Button onClick={onCancel}>Back to question bank</Button><Button variant="outline" onClick={onAnother}><Plus size={16}/>Add another question</Button></section>;
 return <div className="editor-composer" aria-busy={busy}>
 <fieldset disabled={busy} className="editor-fields">
 <section className="editor-section"><div className="editor-section-heading"><span>01</span><div><h2>Question</h2><p>Choose how you want to test your recall.</p></div></div><label>Question type<select value={draft.type} onChange={e=>{field('type',e.target.value);setPreview(false);}}>{questionTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><p className="editor-type-help">{help[draft.type]}</p><label>{draft.type==='flashcard'?'Front of card':'Question prompt'}<textarea value={draft.prompt} onChange={e=>field('prompt',e.target.value)} placeholder={['fill_blank','cloze','fill_blank_options'].includes(draft.type)?'The capital of France is ___.':draft.type==='matching'?'Match each country to its capital.':'What would you like to remember?'}/></label>{['fill_blank','cloze','fill_blank_options'].includes(draft.type)&&<button type="button" className="editor-text-button" onClick={()=>field('prompt',draft.prompt+' ___')}><Plus size={14}/>Insert a blank</button>}
 </section>
 <section className="editor-section"><div className="editor-section-heading"><span>02</span><div><h2>{draft.type==='flashcard'?'Back of card':'Answers'}</h2><p>{help[draft.type]}</p></div></div>
 {['short_answer','fill_blank','flashcard','numeric'].includes(draft.type)&&<label>{draft.type==='flashcard'?'Back of card':'Correct answer'}<textarea value={draft.answer} onChange={e=>field('answer',e.target.value)} placeholder={draft.type==='numeric'?'e.g. 3.14':'Enter the correct answer'}/></label>}
 {draft.type==='numeric'&&<label>Accepted tolerance (±)<input inputMode="decimal" value={draft.numericTolerance} onChange={e=>field('numericTolerance',e.target.value)}/><small>0 means exact. For example, 3.14 ± 0.01.</small></label>}
 {draft.type==='true_false'&&<div className="editor-boolean" role="group" aria-label="Correct answer">{['True','False'].map(x=><button type="button" key={x} aria-pressed={draft.answer===x} onClick={()=>field('answer',x)}>{draft.answer===x&&<Check size={17}/>} {x}</button>)}</div>}
 {['single_choice','multi_select','fill_blank_options'].includes(draft.type)&&<div className="editor-choice-list"><p className="editor-list-label">{draft.type==='fill_blank_options'?'Word bank':'Answer choices'}<small>{draft.type==='multi_select'?'Mark all correct choices':draft.type==='single_choice'?'Mark the correct choice':'Include the answers and optional distractors'}</small></p>{choices.map((choice:string,i:number)=><div className="editor-choice-row" key={i}>{draft.type!=='fill_blank_options'?<input type={draft.type==='single_choice'?'radio':'checkbox'} name="editor-correct-choice" aria-label={`Choice ${i+1} is correct`} checked={!!choice&&(draft.type==='single_choice'?draft.answer===choice:lines('answer').includes(choice))} onChange={e=>markChoice(choice,e.target.checked)} disabled={!choice||busy}/>:<span className="editor-row-number">{i+1}</span>}<input aria-label={`Choice ${i+1}`} value={choice} placeholder={`Choice ${i+1}`} onChange={e=>choiceChange(i,e.target.value)}/><button type="button" aria-label={`Remove choice ${i+1}`} disabled={choices.length<=2} onClick={()=>removeChoice(i)}><Trash2 size={16}/></button></div>)}<button type="button" className="editor-text-button" onClick={()=>field('options',choices.concat('').join('\n'))}><Plus size={15}/>Add choice</button></div>}
 {draft.type==='matching'&&<div className="editor-pairs"><div className="editor-pair-labels"><span>Left side</span><span>Matching answer</span></div>{pairs.map((pair:string[],i:number)=><div className="editor-pair-row" key={i}><input aria-label={`Pair ${i+1} left`} value={pair[0]} placeholder="e.g. Japan" onChange={e=>update('structured',i,e.target.value+'|'+pair[1],2)}/><span>↔</span><input aria-label={`Pair ${i+1} right`} value={pair[1]} placeholder="e.g. Tokyo" onChange={e=>update('structured',i,pair[0]+'|'+e.target.value,2)}/><button type="button" aria-label={`Remove pair ${i+1}`} disabled={pairs.length<=2} onClick={()=>field('structured',steps.filter((_:string,j:number)=>i!==j).join('\n'))}><Trash2 size={15}/></button></div>)}<button type="button" className="editor-text-button" onClick={()=>field('structured',steps.concat('').join('\n'))}><Plus size={15}/>Add pair</button></div>}
 {draft.type==='ordering'&&<div className="editor-sequence">{steps.map((step:string,i:number)=><div className="editor-step-row" key={i}><span className="editor-row-number">{i+1}</span><input aria-label={`Step ${i+1}`} value={step} placeholder={`Step ${i+1}`} onChange={e=>update('structured',i,e.target.value,2)}/><div><button type="button" aria-label={`Move step ${i+1} up`} disabled={i===0} onClick={()=>{const next=[...steps];[next[i-1],next[i]]=[next[i],next[i-1]];field('structured',next.join('\n'));}}><ArrowUp size={14}/></button><button type="button" aria-label={`Move step ${i+1} down`} disabled={i===steps.length-1} onClick={()=>{const next=[...steps];[next[i+1],next[i]]=[next[i],next[i+1]];field('structured',next.join('\n'));}}><ArrowDown size={14}/></button><button type="button" aria-label={`Remove step ${i+1}`} disabled={steps.length<=2} onClick={()=>field('structured',steps.filter((_:string,j:number)=>i!==j).join('\n'))}><Trash2 size={14}/></button></div></div>)}<button type="button" className="editor-text-button" onClick={()=>field('structured',steps.concat('').join('\n'))}><Plus size={15}/>Add step</button></div>}
 {['cloze','fill_blank_options'].includes(draft.type)&&<div className="editor-blanks"><p className="editor-list-label">Blank answers<small>{blankCount?`${blankCount} ${blankCount===1?'gap':'gaps'} in your prompt`:'Add ___ to your question to create a gap'}</small></p>{Array.from({length:blankCount},(_,i)=><label key={i}>Blank {i+1}<input value={lines('structured')[i]||''} onChange={e=>update('structured',i,e.target.value,blankCount)} placeholder="Correct word or phrase"/></label>)}</div>}
 {['short_answer','fill_blank','cloze'].includes(draft.type)&&<details className="editor-details"><summary>Grading options</summary>{draft.type!=='cloze'&&<label>Accepted alternative answers<textarea value={draft.accepted||''} onChange={e=>field('accepted',e.target.value)} placeholder="One accepted answer per line"/></label>}{draft.type!=='numeric'&&<label className="editor-toggle"><input type="checkbox" checked={draft.fuzzy!==false} onChange={e=>field('fuzzy',e.target.checked)}/><span>Accept minor typos<small>One-character typos in words of 5+ letters.</small></span></label>}</details>}
 </section>
 <section className="editor-section"><div className="editor-section-heading"><span>03</span><div><h2>Organize & media</h2><p>Keep your question easy to find.</p></div></div><div className="editor-meta-grid"><label>Subject<input value={draft.subject} onChange={e=>field('subject',e.target.value)} placeholder="e.g. Geography"/></label><label>Topic<input value={draft.topic} onChange={e=>field('topic',e.target.value)} placeholder="e.g. Capitals"/></label></div><label>Tags<input value={draft.tags||''} onChange={e=>field('tags',e.target.value)} placeholder="e.g. revision, chapter 1"/><small>Separate tags with commas.</small></label><details className="editor-details"><summary><ImagePlus size={17}/>Images {draft.image||Object.values(draft.optionImages||{}).some(Boolean)?'· added':''}</summary><ImageUpload label="Question image" image={draft.image} onPick={(file:File)=>upload(file)} onRemove={()=>field('image',undefined)}/>{['single_choice','multi_select'].includes(draft.type)&&choices.filter(Boolean).map((choice:string)=><ImageUpload key={choice} label={`Image for ${choice}`} image={draft.optionImages?.[choice]} onPick={(file:File)=>upload(file,choice)} onRemove={()=>field('optionImages',Object.fromEntries(Object.entries(draft.optionImages||{}).filter(([key])=>key!==choice)))}/>)}{mediaError&&<p role="alert">{mediaError}</p>}</details></section>
 <section className="editor-section editor-ready"><label className="editor-toggle"><input type="checkbox" checked={prepareAudio} onChange={e=>setPrepareAudio(e.target.checked)}/><span><Volume2 size={16}/>Prepare voice when saving<small>Save question and answer audio using your saved voice. First use can take longer.</small></span></label><button type="button" className="editor-text-button" aria-expanded={preview} onClick={()=>setPreview(!preview)}><Eye size={16}/>{preview?'Hide preview':'Preview question'}</button>{preview&&<div className="editor-question-preview"><small>{typeLabel(draft.type)}</small>{draft.image&&<img src={draft.image} alt="Question preview"/>}<h3>{draft.prompt||'Your question appears here'}</h3>{['single_choice','multi_select','fill_blank_options'].includes(draft.type)?choices.filter(Boolean).map((x:string,i:number)=><div key={i} className="editor-preview-choice">{draft.optionImages?.[x]&&<img src={draft.optionImages[x]} alt={x}/>}<span>{String.fromCharCode(65+i)} · {x}</span></div>):draft.type==='matching'?pairs.map((pair:string[],i:number)=><div className="editor-preview-pair" key={i}><span>{pair[0]||'Left side'}</span><span>{pair[1]||'Matching answer'}</span></div>):draft.type==='ordering'?steps.filter(Boolean).map((x:string,i:number)=><div className="editor-preview-choice" key={i}>{i+1}. {x}</div>):draft.type==='true_false'?<div className="editor-preview-pair"><span>True</span><span>False</span></div>:draft.type==='flashcard'?<p>Back · {draft.answer||'Your answer'}</p>:<div className="editor-preview-choice">{['fill_blank','cloze'].includes(draft.type)?'Write the missing answers…':'Write your answer…'}</div>}<small>Editor preview · answers stay hidden during the quiz.</small></div>}</section>
 </fieldset>
 {status&&<p className="editor-save-message" role={busy?'status':'alert'} aria-live="polite">{busy&&<LoaderCircle size={17} className="speech-spinner"/>}{status}</p>}
 <footer className="question-editor-actions"><Button variant="outline" onClick={onCancel} disabled={busy}>Cancel</Button><Button onClick={onSave} disabled={busy}>{busy?<LoaderCircle size={16} className="speech-spinner"/>:<Save size={16}/>} {busy?'Saving…':editing?'Save changes':'Create question'}</Button></footer>
 </div>;
}
