import React,{useState,useRef} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,Check,Save,LoaderCircle,ImagePlus,Eye,EyeOff,Volume2,X,Maximize2,RefreshCw,Link2,Shuffle,Layers,Upload,Crop} from 'lucide-react';
import {ImageEditor} from './ImageEditor';
import {ImageViewer} from './ImageViewer';
import {questionTypes,typeLabel,gradeQuestion} from '../question-types.js';
import {MAX_VARIANTS,emptyDraft,seededShuffle,imageTypes,pictureLabel} from '../question-variants.js';
import {Button} from './components/Button';
import {SpeechButton} from './KokoroPanel';
import {storeImage} from '../sync.js';
const help:any={short_answer:'Ask a direct question and write the answer you expect.',fill_blank:'Use ___ where the missing answer belongs.',single_choice:'Add choices, then select the one correct answer.',flashcard:'Write the front of the card and the answer on the back.',true_false:'Write a statement and choose whether it is true or false.',multi_select:'Add choices and mark every correct answer.',numeric:'Set the expected number and how much variation to accept.',matching:'Each row is a pair. Learners will connect the two sides.',ordering:'Write the steps in their correct order. The quiz will mix them up.',cloze:'Use ___ for each gap, then enter its answer below.',fill_blank_options:'Create gaps with ___ and give learners a word bank.'};
const imageAccept='image/png,image/jpeg,image/webp,image/gif,image/avif,image/bmp';
// Stored images live in localStorage (about 5 MB in total), so keep each one small.
export async function compressImage(file:File):Promise<string>{
 if(!file.type.startsWith('image/'))throw new Error('Choose an image file (PNG, JPEG, WebP or GIF).');
 if(file.size>25*1024*1024)throw new Error('Choose an image under 25 MB.');
 const url=URL.createObjectURL(file);
 try{
  const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('This image could not be opened. Try a PNG, JPEG or WebP file.'));i.src=url;});
  const width=img.naturalWidth,height=img.naturalHeight;
  if(['image/png','image/jpeg','image/webp'].includes(file.type)&&file.size<=250*1024&&Math.max(width,height)<=1280)return await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Could not read this image.'));r.readAsDataURL(file);});
  for(const [max,quality] of [[1280,.82],[1024,.78],[800,.72],[640,.65]]){
   const scale=Math.min(1,max/Math.max(width,height)),canvas=document.createElement('canvas');
   canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));
   const ctx=canvas.getContext('2d');if(!ctx)throw new Error('This browser cannot process images.');
   ctx.drawImage(img,0,0,canvas.width,canvas.height);
   let data=canvas.toDataURL('image/webp',quality);
   if(!data.startsWith('data:image/webp')){ctx.globalCompositeOperation='destination-over';ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);data=canvas.toDataURL('image/jpeg',quality);}
   if(data.length<=450000)return data;
  }
  throw new Error('This image is too detailed to store. Try cropping it first.');
 }finally{URL.revokeObjectURL(url);}
}
// Copies the picture into the question when the site allows it; otherwise keeps the https link.
export async function imageFromLink(link:string):Promise<{image:string;linked:boolean}>{
 let url:URL;try{url=new URL(link.trim());}catch{throw new Error('Paste a full image link that starts with https://');}
 if(!['https:','http:'].includes(url.protocol))throw new Error('Paste a full image link that starts with https://');
 try{
  const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),10000);
  const response=await fetch(url.href,{mode:'cors',signal:controller.signal}).finally(()=>window.clearTimeout(timer));
  const blob=await response.blob();
  if(response.ok&&blob.type.startsWith('image/'))return {image:await compressImage(new File([blob],'linked-image',{type:blob.type})),linked:false};
 }catch{}
 if(url.protocol!=='https:')throw new Error('This site blocks copying the image. Use an https:// link or upload the file.');
 if(url.href.length>2048)throw new Error('This link is too long. Upload the image instead.');
 await new Promise<void>((resolve,reject)=>{const img=new Image(),timer=window.setTimeout(()=>reject(new Error('The image took too long to load.')),12000);img.onload=()=>{window.clearTimeout(timer);resolve();};img.onerror=()=>{window.clearTimeout(timer);reject(new Error('No image was found at this link.'));};img.src=url.href;});
 return {image:url.href,linked:true};
}
export function ImageLightbox({src,onClose}:{src:string|null;onClose:()=>void}){
 return src?<ImageViewer src={src} alt="Enlarged preview" onClose={onClose}/>:null;
}
function ImageLinkForm({onSubmit,onCancel,label='Image link'}:any){
 const [url,setUrl]=useState(''),[busy,setBusy]=useState(false);
 const submit=async()=>{if(!url.trim()||busy)return;setBusy(true);try{await onSubmit(url.trim());}finally{setBusy(false);}};
 return <div className="editor-image-link"><Link2 size={15} aria-hidden="true"/><input type="url" inputMode="url" autoFocus aria-label={label} placeholder="https://…/picture.jpg" value={url} disabled={busy} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void submit();}if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onCancel();}}}/><button type="button" className="is-primary" disabled={!url.trim()||busy} onClick={submit}>{busy?<LoaderCircle size={14} className="speech-spinner"/>:'Add'}</button><button type="button" aria-label="Cancel image link" disabled={busy} onClick={onCancel}><X size={14}/></button></div>;
}
function InlineImage({label,hint,image,onPick,onLink,onRemove,onView,onEdit}:any){
 const input=useRef<HTMLInputElement>(null),[loading,setLoading]=useState(false),[linking,setLinking]=useState(false);
 const pick=async(file?:File)=>{if(!file)return;setLoading(true);try{await onPick(file);}finally{setLoading(false);}};
 return <div className={`editor-inline-image${image?' has-image':''}${linking?' is-linking':''}`}>
  {image?<button type="button" className="editor-inline-thumb" aria-label={`Enlarge ${label.toLowerCase()}`} onClick={()=>onView(image)}><img src={image} alt=""/><span><Maximize2 size={13}/></span></button>:<span className="editor-inline-icon"><ImagePlus size={18}/></span>}
  <div className="editor-inline-copy"><strong>{label}</strong><small>{image?(image.startsWith('https:')?'Linked image · tap to preview':'Tap the image to preview it'):hint}</small></div>
  <div className="editor-inline-actions">{image&&onEdit&&<button type="button" aria-label={`Edit ${label.toLowerCase()}`} disabled={loading} onClick={onEdit}><Crop size={14}/>Edit</button>}<button type="button" disabled={loading} onClick={()=>input.current?.click()}>{loading?<LoaderCircle size={14} className="speech-spinner"/>:image?<RefreshCw size={14}/>:<Upload size={14}/>}{loading?'Adding…':image?'Change':'Upload'}</button>{!image&&<button type="button" aria-label={`Add ${label.toLowerCase()} from a link`} aria-expanded={linking} onClick={()=>setLinking(v=>!v)}><Link2 size={14}/>Link</button>}{image&&<button type="button" className="is-remove" aria-label={`Remove ${label.toLowerCase()}`} disabled={loading} onClick={onRemove}><Trash2 size={14}/></button>}</div>
  {linking&&!image&&<ImageLinkForm label={`${label} link`} onCancel={()=>setLinking(false)} onSubmit={async(url:string)=>{if(await onLink(url))setLinking(false);}}/>}
  <input ref={input} type="file" hidden aria-label={`Upload ${label.toLowerCase()}`} accept={imageAccept} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void pick(file);}}/>
 </div>;
}
function ChoiceImageButton({choice,image,onPick,onLink,onRemove,onView,onEdit,disabled}:any){
 const input=useRef<HTMLInputElement>(null),[loading,setLoading]=useState(false),[menu,setMenu]=useState<''|'menu'|'link'|'image'>(''),box=useRef<HTMLSpanElement>(null);
 React.useEffect(()=>{if(!menu)return;const close=(e:PointerEvent)=>{if(!box.current?.contains(e.target as Node))setMenu('');};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[menu]);
 return <span className="editor-choice-image" ref={box}>
  {image?<button type="button" className="editor-choice-thumb" aria-label={`Image options for ${choice}`} aria-expanded={menu==='image'} onClick={()=>setMenu(m=>m?'':'image')}><img src={image} alt=""/></button>:<button type="button" className="editor-choice-add" aria-label={`Add image for ${choice||'this item'}`} aria-expanded={!!menu} title={disabled?'Type the choice first':'Add image'} disabled={disabled||loading} onClick={()=>setMenu(m=>m?'':'menu')}>{loading?<LoaderCircle size={15} className="speech-spinner"/>:<ImagePlus size={16}/>}</button>}
  {image&&<button type="button" className="editor-choice-image-remove" aria-label={`Remove image for ${choice}`} onClick={onRemove}><X size={11}/></button>}
  {menu&&<span className="editor-choice-image-menu" role="menu" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();setMenu('');}}}>{menu==='image'?<><button type="button" role="menuitem" onClick={()=>{setMenu('');onView(image);}}><Maximize2 size={15}/>Preview</button>{onEdit&&<button type="button" role="menuitem" onClick={()=>{setMenu('');onEdit();}}><Crop size={15}/>Edit image</button>}<button type="button" role="menuitem" onClick={()=>{setMenu('');input.current?.click();}}><RefreshCw size={15}/>Replace image</button></>:menu==='menu'?<><button type="button" role="menuitem" onClick={()=>{setMenu('');input.current?.click();}}><Upload size={15}/>Upload image</button><button type="button" role="menuitem" onClick={()=>setMenu('link')}><Link2 size={15}/>Use image link</button></>:<ImageLinkForm label={`Image link for ${choice}`} onCancel={()=>setMenu('')} onSubmit={async(url:string)=>{setLoading(true);try{if(await onLink(url))setMenu('');}finally{setLoading(false);}}}/>}</span>}
  <input ref={input} type="file" hidden accept={imageAccept} onChange={async e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file){setLoading(true);try{await onPick(file);}finally{setLoading(false);}}}}/>
 </span>;
}
function ImageUpload({label,image,onPick,onLink,onRemove,onEdit,hint='PNG, JPEG, WebP or GIF · resized automatically'}:any){
 const input=useRef<HTMLInputElement>(null),[loading,setLoading]=useState(false),[linking,setLinking]=useState(false);
 return <div className="editor-image-upload"><div className={`editor-upload-preview ${image?'has-image':''}`}>
 {image?<img src={image} alt={`${label} preview`}/>:<><ImagePlus size={31}/><span>No image added</span></>}
 </div><div className="editor-upload-bottom"><div><strong>{label}</strong><small>{hint}</small></div><div className="editor-upload-buttons">{image&&onEdit&&<button type="button" className="editor-upload-choose is-secondary" disabled={loading} aria-label={`Edit ${label.toLowerCase()}`} onClick={onEdit}><Crop size={15}/>Edit</button>}<button type="button" className="editor-upload-choose" disabled={loading} aria-label={`${image?'Change':'Choose'} ${label.toLowerCase()}`} onClick={()=>input.current?.click()}>{loading?<LoaderCircle size={15} className="speech-spinner"/>:<Upload size={15}/>}{loading?'Adding…':image?'Change':'Upload'}</button>{!image&&<button type="button" className="editor-upload-choose is-secondary" aria-expanded={linking} onClick={()=>setLinking(v=>!v)}><Link2 size={15}/>Link</button>}</div></div>
 {linking&&!image&&<ImageLinkForm label={`${label} link`} onCancel={()=>setLinking(false)} onSubmit={async(url:string)=>{if(await onLink(url))setLinking(false);}}/>}
 {image&&<button type="button" className="editor-upload-remove" aria-label={`Remove ${label.toLowerCase()}`} disabled={loading} onClick={onRemove}><Trash2 size={14}/>Remove image</button>}
 <input ref={input} type="file" aria-label={`Upload ${label.toLowerCase()}`} accept={imageAccept} onChange={async e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file){setLoading(true);try{await onPick(file);}finally{setLoading(false);}}}}/>
 </div>;
}
function FlashcardEditorPreview({draft}:any){
 const [showBack,setShowBack]=useState(false);
 return <div className="editor-question-preview"><small>Flashcard · tap to flip</small>{draft.image&&<img src={draft.image} alt="Flashcard image"/>}<button type="button" className="editor-flashcard-preview" aria-pressed={showBack} aria-label={showBack?'Show flashcard front':'Show flashcard back'} onClick={()=>setShowBack(value=>!value)}><span className={`editor-flashcard-preview-inner${showBack?' is-back':''}`}><span className="editor-flashcard-preview-face editor-flashcard-front"><small>FRONT · QUESTION</small><strong>{draft.prompt||'Your question appears here'}</strong><em>Tap to reveal the answer</em></span><span className="editor-flashcard-preview-face editor-flashcard-back"><small>BACK · ANSWER</small>{draft.answerImage&&<img className="editor-flashcard-answer-image" src={draft.answerImage} alt=""/>}<strong>{draft.answer||'Your answer appears here'}</strong><em>Tap to see the question</em></span></span></button></div>;
}

function QuestionTypePreview({draft,choices,pairs,steps}:any){
 const type=draft.type,blanks=String(draft.structured||'').split('\n').map((x:string)=>x.trim()).filter(Boolean),options=type==='true_false'?['True','False']:choices.filter(Boolean),answerList=String(draft.answer||'').split('\n').filter(Boolean);
 const item={...draft,answer:draft.answer||'',options,correctAnswers:type==='multi_select'?answerList:undefined,acceptedAnswers:String(draft.accepted||'').split('\n').filter(Boolean),fuzzy:draft.fuzzy!==false,numericTolerance:Number(draft.numericTolerance||0),pairs:pairs.map((p:string[])=>({left:p[0],right:p[1]})),sequence:steps.filter(Boolean),blanks};
 const start=()=>type==='ordering'?seededShuffle(steps.filter(Boolean),draft.prompt):['cloze','fill_blank_options'].includes(type)?Array(blanks.length).fill(''):type==='multi_select'?[]:type==='matching'?Array(pairs.length).fill(''):'';
 const [value,setValue]=useState<any>(start),[revealed,setRevealed]=useState(false);
 React.useEffect(()=>{setValue(start());setRevealed(false);},[type,draft.prompt,draft.answer,draft.options,draft.structured]);
 const complete=type==='multi_select'?value.length>0:['cloze','fill_blank_options','matching','ordering'].includes(type)?Array.isArray(value)&&value.length>0&&value.every(Boolean):String(value).trim().length>0;
 const correct=()=>{try{return gradeQuestion(item,value);}catch{return false;}};
 const updateAt=(i:number,next:string)=>setValue((old:any)=>{const copy=Array.isArray(old)?[...old]:[];copy[i]=next;return copy;});
 const check=<div className="editor-preview-actions"><button type="button" className="editor-preview-check" disabled={!complete||revealed} onClick={()=>setRevealed(true)}>{revealed?(correct()?'Correct':'Not quite'):'Check answer'}</button>{revealed&&<button type="button" className="editor-preview-reset" onClick={()=>{setValue(start());setRevealed(false);}}><RefreshCw size={14}/>Try again</button>}</div>;
 if(type==='flashcard')return <FlashcardEditorPreview draft={draft}/>;
 const matchOptions=seededShuffle(pairs.map((p:string[])=>p[1]),draft.prompt+'|m');
 return <div className="editor-question-preview"><small>{typeLabel(type)}</small>{draft.image&&<img src={draft.image} alt="Question preview"/>}<h3>{draft.prompt||'Your question appears here'}</h3>
 {['single_choice','true_false','multi_select'].includes(type)&&<div className="editor-preview-options">{options.map((x:string,i:number)=>{const picked=type==='multi_select'?value.includes(x):value===x,isCorrect=type==='multi_select'?answerList.includes(x):draft.answer===x;return <button type="button" key={i} className={`editor-preview-option${picked?' is-selected':''}${revealed&&isCorrect?' is-correct':''}${revealed&&picked&&!isCorrect?' is-wrong':''}`} aria-pressed={picked} onClick={()=>!revealed&&setValue((old:any)=>type==='multi_select'?(old.includes(x)?old.filter((v:string)=>v!==x):[...old,x]):x)}>{draft.optionImages?.[x]&&<img src={draft.optionImages[x]} alt=""/>}<span>{String.fromCharCode(65+i)} · {x}</span></button>})}{check}</div>}
 {type==='fill_blank'&&<div className="editor-preview-interaction"><p className="editor-preview-sentence">{draft.prompt.split(/_{2,}/g).length>1?draft.prompt.split(/_{2,}/g).map((part:string,i:number,all:string[])=><React.Fragment key={i}>{part}{i<all.length-1&&<input aria-label="Answer the blank" value={value} disabled={revealed} onChange={e=>setValue(e.target.value)} placeholder="…"/>}</React.Fragment>):<input aria-label="Answer the blank" value={value} disabled={revealed} onChange={e=>setValue(e.target.value)} placeholder="Type the missing word"/>}</p>{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {draft.answer||'Add the answer above'}</small>}</div>}
 {type==='numeric'&&<div className="editor-preview-interaction"><label className="editor-preview-answer-label">Your answer<input aria-label="Preview numeric answer" inputMode="decimal" value={value} disabled={revealed} onChange={e=>setValue(e.target.value)} placeholder="Enter a number…"/></label>{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {draft.answer||'Add the answer above'}{Number(draft.numericTolerance)>0?` (±${draft.numericTolerance})`:''}</small>}</div>}
 {type==='short_answer'&&<div className="editor-preview-interaction"><label className="editor-preview-answer-label">Your answer<textarea aria-label="Preview short answer" value={value} disabled={revealed} onChange={e=>setValue(e.target.value)} placeholder="Write what you remember…"/></label>{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {draft.answer||'Add the answer above'}</small>}</div>}
 {['cloze','fill_blank_options'].includes(type)&&<div className="editor-preview-interaction"><p className="editor-preview-sentence">{draft.prompt.split(/_{2,}/g).map((part:string,i:number,all:string[])=><React.Fragment key={i}>{part}{i<all.length-1&&(type==='cloze'?<input aria-label={`Blank ${i+1}`} value={value[i]||''} disabled={revealed} onChange={e=>updateAt(i,e.target.value)}/>:<button type="button" className="editor-preview-gap" aria-label={`Blank ${i+1}`} disabled={revealed} onClick={()=>updateAt(i,'')}>{value[i]||`Blank ${i+1}`}</button>)}</React.Fragment>)}</p>{type==='fill_blank_options'&&<div className="editor-preview-options is-bank">{options.map((x:string,i:number)=><button type="button" className={`editor-preview-option${value.includes(x)?' is-selected':''}`} key={i} disabled={revealed} onClick={()=>{const empty=value.findIndex((v:string)=>!v);if(empty>=0)updateAt(empty,x);}}>{draft.optionImages?.[x]&&<img src={draft.optionImages[x]} alt=""/>}<span>{x}</span></button>)}</div>}{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {blanks.join(' · ')||'Add a blank answer above'}</small>}</div>}
 {type==='matching'&&<div className="editor-preview-interaction">{pairs.map((pair:string[],i:number)=><label className="editor-preview-match" key={i}><span>{draft.optionImages?.[pair[0].trim()]&&<img src={draft.optionImages[pair[0].trim()]} alt=""/>}{pair[0]||'Left side'}</span><select aria-label={`Match ${pair[0]||i+1}`} value={value[i]||''} disabled={revealed} onChange={e=>updateAt(i,e.target.value)}><option value="">Choose a match</option>{matchOptions.map((p:string,j:number)=><option key={j} value={p}>{p||'Matching answer'}</option>)}</select></label>)}{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Matches: {pairs.map((p:string[])=>`${p[0]} → ${p[1]}`).join(' · ')}</small>}</div>}
 {type==='ordering'&&<div className="editor-preview-interaction editor-preview-order">{value.map((x:string,i:number)=><div className="editor-preview-option" key={`${i}-${x}`}><span>{draft.optionImages?.[x]&&<img src={draft.optionImages[x]} alt=""/>}{i+1} · {x||'Step'}</span><div><button type="button" aria-label="Move step up" disabled={revealed||i===0} onClick={()=>setValue((old:string[])=>{const n=[...old];[n[i-1],n[i]]=[n[i],n[i-1]];return n;})}>↑</button><button type="button" aria-label="Move step down" disabled={revealed||i===value.length-1} onClick={()=>setValue((old:string[])=>{const n=[...old];[n[i+1],n[i]]=[n[i],n[i+1]];return n;})}>↓</button></div></div>)}{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Correct order: {steps.filter(Boolean).join(' → ')}</small>}</div>}
 {revealed&&draft.answerImage&&<img className="editor-preview-answer-image" src={draft.answerImage} alt="Answer illustration"/>}
 </div>;
}

const textTypes=['short_answer','fill_blank','flashcard','numeric'];
function seedVariant(type:string,base:any){
 const next:any=emptyDraft(type,base.prompt||'');
 const answer=['short_answer','fill_blank','flashcard','single_choice','numeric'].includes(base.type)?String(base.answer||'').trim():'';
 if(textTypes.includes(type)&&answer&&(type!=='numeric'||/^[-+.\d]/.test(answer)))next.answer=answer;
 if(['single_choice','multi_select'].includes(type)){
  if(['single_choice','multi_select'].includes(base.type)){next.options=base.options;next.optionImages=base.optionImages||{};next.answer=type===base.type||type==='multi_select'?base.answer:String(base.answer).split('\n')[0]||'';}
  else if(answer){next.options=answer+'\n';next.answer=answer;}
 }
 if(['matching','ordering'].includes(type)&&base.type===type)next.structured=base.structured;
 return next;
}

export function QuestionEditor({draft,setDraft,onSave,onCancel,busy,status,saved,editing,prepareAudio,setPrepareAudio,onAnother}:any){
 const [preview,setPreview]=useState(false),[mediaError,setMediaError]=useState(''),[mediaNote,setMediaNote]=useState(''),[step,setStep]=useState(0),[zoom,setZoom]=useState<string|null>(null),[vi,setVi]=useState(0),[addingType,setAddingType]=useState(false),[editImg,setEditImg]=useState<{src:string;key?:string;target:'image'|'answerImage';temp?:boolean}|null>(null);
 const tabs=useRef<HTMLDivElement>(null);
 const tabLabels=['Question','Images','Optional'];
 const variants:any[]=draft.variants||[];
 const active=Math.min(vi,variants.length),d=active===0?draft:variants[active-1];
 const allTypes=[draft,...variants];
 function goStep(next:number){setStep(next);tabs.current?.scrollIntoView({block:'start',behavior:'smooth'});}
 function tabKey(e:React.KeyboardEvent,index:number){let next=index;if(e.key==='ArrowRight')next=(index+1)%tabLabels.length;else if(e.key==='ArrowLeft')next=(index+tabLabels.length-1)%tabLabels.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabLabels.length-1;else return;e.preventDefault();goStep(next);(tabs.current?.querySelectorAll('button')[next] as HTMLButtonElement)?.focus();}
 const setD=(fn:(v:any)=>any)=>setDraft((x:any)=>active===0?fn(x):{...x,variants:(x.variants||[]).map((v:any,i:number)=>i===active-1?fn(v):v)});
 const field=(key:string,value:any)=>setD((v:any)=>({...v,[key]:value}));
 const shared=(key:string,value:any)=>setDraft((x:any)=>({...x,[key]:value}));
 const lines=(key:string,min=0)=>{const rows=String(d[key]||'').split('\n');while(rows.length<min)rows.push('');return rows;};
 const update=(key:string,i:number,value:string,min=0)=>{const rows=lines(key,min);rows[i]=value;field(key,rows.join('\n'));};
 const choices=lines('options',2),steps=lines('structured',2),blankCount=(String(d.prompt||'').match(/_{2,}/g)||[]).length;
 const pairs=steps.map((line:string)=>{const [left='',...rest]=line.split('|');return [left,rest.join('|')];});
 function structuredChange(i:number,value:string){const rows=lines('structured',2),old=rows[i];rows[i]=value;setD((v:any)=>{let imgs={...(v.optionImages||{})};const move=(a:string,b:string)=>{a=a.trim();b=b.trim();if(a!==b&&imgs[a]){imgs[b]=imgs[a];delete imgs[a];}};if(v.type==='matching'){const [ol='',...or]=old.split('|'),[nl='',...nr]=value.split('|');move(ol,nl);move(or.join('|'),nr.join('|'));}else move(old,value);return {...v,structured:rows.join('\n'),optionImages:imgs};});}
 const markChoice=(choice:string,on:boolean)=>{if(d.type==='single_choice')field('answer',choice);else{const answers=lines('answer').filter(Boolean);field('answer',(on?[...new Set([...answers,choice])]:answers.filter((x:string)=>x!==choice)).join('\n'));}};
 function choiceChange(i:number,value:string){const old=choices[i],next=[...choices];next[i]=value;setD((v:any)=>({...v,options:next.join('\n'),answer:v.type==='single_choice'?(v.answer===old?value:v.answer):String(v.answer).split('\n').map((x:string)=>x===old?value:x).join('\n'),optionImages:old&&v.optionImages?.[old]?{...v.optionImages,[old]:undefined,[value]:v.optionImages[old]}:v.optionImages}));}
 function removeChoice(i:number){const old=choices[i];setD((v:any)=>({...v,options:choices.filter((_:string,j:number)=>j!==i).join('\n'),answer:v.type==='single_choice'?(v.answer===old?'':v.answer):String(v.answer).split('\n').filter((x:string)=>x!==old).join('\n'),optionImages:Object.fromEntries(Object.entries(v.optionImages||{}).filter(([k])=>k!==old&&v.optionImages[k]))}));}
 async function place(data:string,key?:string,target:'image'|'answerImage'='image'){const image=await storeImage(data).catch(()=>data);if(key)setD((v:any)=>({...v,optionImages:{...v.optionImages,[key]:image}}));else shared(target,image);}
 async function upload(file:File,key?:string,target:'image'|'answerImage'='image'){
  setMediaError('');setMediaNote('');
  if(!file.type.startsWith('image/')){setMediaError('Choose an image file (PNG, JPEG, WebP or GIF).');return;}
  if(file.size>25*1024*1024){setMediaError('Choose an image under 25 MB.');return;}
  setEditImg({src:URL.createObjectURL(file),key,target,temp:true});
 }
 async function link(url:string,key?:string,target:'image'|'answerImage'='image'){setMediaError('');try{const {image,linked}=await imageFromLink(url);if(linked){await place(image,key,target);setMediaNote('This site only allows linking, so the picture appears when you are online.');}else{setMediaNote('');setEditImg({src:image,key,target});}return true;}catch(e:any){setMediaError(e.message);return false;}}
 function closeEditor(){if(editImg?.temp)URL.revokeObjectURL(editImg.src);setEditImg(null);}
 const removeChoiceImage=(choice:string)=>field('optionImages',Object.fromEntries(Object.entries(d.optionImages||{}).filter(([key])=>key!==choice)));
 const choiceImages=imageTypes.includes(d.type);
 function nameChoice(i:number,choice:string){if(choice.trim())return choice;const name=pictureLabel(i+1);choiceChange(i,name);return name;}
 const imageButton=(text:string,label=text,name?:()=>string)=>{const key=text.trim(),keyFor=()=>key||name!();return <ChoiceImageButton choice={label} disabled={!key&&!name} image={d.optionImages?.[key]} onPick={(file:File)=>upload(file,keyFor())} onLink={(url:string)=>link(url,keyFor())} onRemove={()=>removeChoiceImage(key)} onView={setZoom} onEdit={()=>setEditImg({src:d.optionImages[key],key,target:'image'})}/>;};
 const imageList=d.type==='matching'?{title:'Pair images',hint:'Add a picture to either side of a pair.'}:d.type==='ordering'?{title:'Step images',hint:'Each picture appears on its step.'}:d.type==='fill_blank_options'?{title:'Word bank images',hint:'Each picture appears on its word in the word bank.'}:{title:'Choice images',hint:'Each picture appears inside its answer choice.'};
 function pasteImage(e:React.ClipboardEvent){const file=[...e.clipboardData.files].find(f=>f.type.startsWith('image/'));if(file){e.preventDefault();void upload(file);}}
 function addType(type:string){setDraft((x:any)=>({...x,typeMode:x.typeMode||'random',variants:[...(x.variants||[]),seedVariant(type,active===0?x:x.variants[active-1])]}));setVi(variants.length+1);setAddingType(false);setPreview(false);}
 function removeType(){setDraft((x:any)=>{const rest=(x.variants||[]).filter((_:any,i:number)=>i!==active-1);return {...x,variants:rest.length?rest:undefined};});setVi(Math.max(0,active-1));}
 function makeMain(){setDraft((x:any)=>{const list=[x,...(x.variants||[])],main=list[active],{type,prompt,answer,options,numericTolerance,structured,accepted,fuzzy,optionImages}=x;const old={type,prompt,answer,options,numericTolerance,structured,accepted,fuzzy,optionImages};const rest=(x.variants||[]).map((v:any,i:number)=>i===active-1?old:v);return {...x,...main,variants:rest};});setVi(0);}
 const statusId='editor-status';
 if(saved)return <section className="editor-success" role="status"><span className="editor-success-icon"><Check size={30}/></span><h2>{editing?'Question updated':'Question created'}</h2><p>{status}</p><div className="editor-saved-question"><small>{[saved.type,...(saved.variants||[]).map((v:any)=>v.type)].map(typeLabel).join(' · ')}</small><strong>{saved.prompt}</strong><SpeechButton questionId={saved.id} text={saved.prompt} spokenText={saved.type==='fill_blank'?saved.prompt.replace(/_{2,}/g,'blank'):undefined} label="Play saved question audio"/></div><Button onClick={onCancel}>Back to question bank</Button><Button variant="outline" onClick={()=>{setStep(0);setVi(0);setPreview(false);setMediaError('');setMediaNote('');onAnother();}}><Plus size={16}/>Add another question</Button></section>;
 return <div className="editor-composer" aria-busy={busy}>
 <fieldset disabled={busy} className="editor-fields">
 <div className="editor-tabs editor-numbered-steps" ref={tabs} role="tablist" aria-label="Question editor sections">{tabLabels.map((label,i)=><button type="button" key={label} role="tab" id={`editor-tab-${i}`} aria-selected={step===i} aria-controls={`editor-panel-${i}`} tabIndex={step===i?0:-1} onClick={()=>goStep(i)} onKeyDown={e=>tabKey(e,i)}><span>{i+1}</span>{label}</button>)}</div>
 <section className="editor-section editor-step-panel" role="tabpanel" id="editor-panel-0" aria-labelledby="editor-tab-0" hidden={step!==0}>
 <div className="editor-variants">
  <div className="editor-variants-head"><span><Layers size={15}/>Ways to ask this question</span>{variants.length<MAX_VARIANTS&&<button type="button" className="editor-variant-add" aria-expanded={addingType} onClick={()=>setAddingType(v=>!v)}><Plus size={14}/>Add type</button>}</div>
  {allTypes.length>1&&<div className="editor-variant-tabs" role="tablist" aria-label="Question types">{allTypes.map((v:any,i:number)=><button type="button" role="tab" key={i} aria-selected={active===i} onClick={()=>{setVi(i);setPreview(false);}}><span>{i+1}</span>{typeLabel(v.type)}</button>)}</div>}
  {addingType&&<div className="editor-variant-picker" role="group" aria-label="Choose another question type">{questionTypes.map(([id,label])=><button type="button" key={id} onClick={()=>addType(id)}>{label}</button>)}</div>}
  {allTypes.length>1&&<div className="editor-variant-mode" role="radiogroup" aria-label="Type used in quizzes"><button type="button" role="radio" aria-checked={draft.typeMode!=='primary'} onClick={()=>shared('typeMode','random')}><Shuffle size={14}/>Random each quiz</button><button type="button" role="radio" aria-checked={draft.typeMode==='primary'} onClick={()=>shared('typeMode','primary')}><span className="editor-variant-one">1</span>Always type 1</button></div>}
 </div>
 <div className="editor-type-row"><label>{allTypes.length>1?`Type ${active+1}`:'Question type'}<select value={d.type} onChange={e=>{field('type',e.target.value);setPreview(false);}}>{questionTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{active>0&&<div className="editor-type-actions"><button type="button" onClick={makeMain}>Make type 1</button><button type="button" className="is-remove" onClick={removeType}><Trash2 size={14}/>Remove</button></div>}</div>
 <p className="editor-type-help">{help[d.type]}</p>
 <label>{d.type==='flashcard'?'Front of card':'Question prompt'}{d.image&&!['fill_blank','cloze','fill_blank_options'].includes(d.type)&&<small className="editor-optional">Optional — the picture can be the question</small>}<textarea value={d.prompt} onChange={e=>field('prompt',e.target.value)} onPaste={pasteImage} placeholder={['fill_blank','cloze','fill_blank_options'].includes(d.type)?'The capital of France is ___.':d.type==='matching'?'Match each country to its capital.':'What would you like to remember?'}/></label>{['fill_blank','cloze','fill_blank_options'].includes(d.type)&&<button type="button" className="editor-text-button" onClick={()=>field('prompt',String(d.prompt||'').trimEnd()+' ___')}><Plus size={14}/>Insert a blank</button>}
 {active===0&&<InlineImage label={d.type==='flashcard'?'Front image':'Question image'} hint={allTypes.length>1?'Optional · shown for every type':'Optional · you can also paste an image'} image={draft.image} onPick={(file:File)=>upload(file)} onLink={(url:string)=>link(url)} onRemove={()=>shared('image',undefined)} onView={setZoom} onEdit={()=>setEditImg({src:draft.image,target:'image'})}/>}
 {mediaError&&step===0&&<p className="editor-media-error" role="alert">{mediaError}</p>}{mediaNote&&step===0&&<p className="editor-media-note" role="status">{mediaNote}</p>}
 <div className="editor-answer-fields">
 {textTypes.includes(d.type)&&<label>{d.type==='flashcard'?'Back of card':'Correct answer'}{d.type==='flashcard'&&d.answerImage&&<small className="editor-optional">Optional — the answer picture is enough</small>}<textarea value={d.answer} onChange={e=>field('answer',e.target.value)} placeholder={d.type==='numeric'?'e.g. 3.14':'Enter the correct answer'}/></label>}
 {d.type==='numeric'&&<label>Accepted tolerance (±)<input inputMode="decimal" value={d.numericTolerance} onChange={e=>field('numericTolerance',e.target.value)}/><small>0 means exact. For example, 3.14 ± 0.01.</small></label>}
 {d.type==='true_false'&&<div className="editor-boolean" role="group" aria-label="Correct answer">{['True','False'].map(x=><button type="button" key={x} aria-pressed={d.answer===x} onClick={()=>field('answer',x)}>{d.answer===x&&<Check size={17}/>} {x}</button>)}</div>}
 {['single_choice','multi_select','fill_blank_options'].includes(d.type)&&<div className="editor-choice-list"><p className="editor-list-label">{d.type==='fill_blank_options'?'Word bank':'Answer choices'}<small>{d.type==='multi_select'?'Mark every correct choice':d.type==='single_choice'?'Mark the correct choice':'Include the answers and a few distractors'}</small></p>{choices.map((choice:string,i:number)=><div className="editor-choice-row" key={i}>{d.type!=='fill_blank_options'?<input type={d.type==='single_choice'?'radio':'checkbox'} name={`editor-correct-choice-${active}`} aria-label={`Choice ${i+1} is correct`} checked={!!choice&&(d.type==='single_choice'?d.answer===choice:lines('answer').includes(choice))} onChange={e=>markChoice(choice,e.target.checked)} disabled={!choice||busy}/>:<span className="editor-row-number">{i+1}</span>}<input aria-label={`Choice ${i+1}`} value={choice} placeholder={`Choice ${i+1}`} onChange={e=>choiceChange(i,e.target.value)}/>{choiceImages&&<ChoiceImageButton choice={choice||`choice ${i+1}`} disabled={!!choice.trim()&&choices.filter((c:string)=>c===choice).length>1} image={d.optionImages?.[choice]} onPick={(file:File)=>upload(file,nameChoice(i,choice))} onLink={(url:string)=>link(url,nameChoice(i,choice))} onRemove={()=>removeChoiceImage(choice)} onView={setZoom} onEdit={()=>setEditImg({src:d.optionImages[choice],key:choice,target:'image'})}/>}<button type="button" aria-label={`Remove choice ${i+1}`} disabled={choices.length<=2} onClick={()=>removeChoice(i)}><Trash2 size={16}/></button></div>)}<button type="button" className="editor-text-button" onClick={()=>field('options',choices.concat('').join('\n'))}><Plus size={15}/>Add choice</button></div>}
 {d.type==='matching'&&<div className="editor-pairs"><div className="editor-pair-labels"><span>Left side</span><span>Matching answer</span></div>{pairs.map((pair:string[],i:number)=><div className="editor-pair-row" key={i}><input aria-label={`Pair ${i+1} left`} value={pair[0]} placeholder="e.g. Japan" onChange={e=>structuredChange(i,e.target.value+'|'+pair[1])}/><span>↔</span><input aria-label={`Pair ${i+1} right`} value={pair[1]} placeholder="e.g. Tokyo" onChange={e=>structuredChange(i,pair[0]+'|'+e.target.value)}/><button type="button" aria-label={`Remove pair ${i+1}`} disabled={pairs.length<=2} onClick={()=>field('structured',steps.filter((_:string,j:number)=>i!==j).join('\n'))}><Trash2 size={15}/></button></div>)}<div className="editor-pair-footer"><button type="button" className="editor-text-button" onClick={()=>field('structured',steps.concat('').join('\n'))}><Plus size={15}/>Add pair</button><button type="button" className="editor-text-button" onClick={()=>goStep(1)}><ImagePlus size={15}/>{Object.values(d.optionImages||{}).some(Boolean)?'Edit pair images':'Add pictures'}</button></div></div>}
 {d.type==='ordering'&&<div className="editor-sequence">{steps.map((s:string,i:number)=><div className="editor-step-row" key={i}><span className="editor-row-number">{i+1}</span><input aria-label={`Step ${i+1}`} value={s} placeholder={`Step ${i+1}`} onChange={e=>structuredChange(i,e.target.value)}/><div>{imageButton(s,s||`step ${i+1}`,()=>{const n=pictureLabel(i+1);structuredChange(i,n);return n;})}<button type="button" aria-label={`Move step ${i+1} up`} disabled={i===0} onClick={()=>{const next=[...steps];[next[i-1],next[i]]=[next[i],next[i-1]];field('structured',next.join('\n'));}}><ArrowUp size={14}/></button><button type="button" aria-label={`Move step ${i+1} down`} disabled={i===steps.length-1} onClick={()=>{const next=[...steps];[next[i+1],next[i]]=[next[i],next[i+1]];field('structured',next.join('\n'));}}><ArrowDown size={14}/></button><button type="button" aria-label={`Remove step ${i+1}`} disabled={steps.length<=2} onClick={()=>field('structured',steps.filter((_:string,j:number)=>i!==j).join('\n'))}><Trash2 size={14}/></button></div></div>)}<button type="button" className="editor-text-button" onClick={()=>field('structured',steps.concat('').join('\n'))}><Plus size={15}/>Add step</button></div>}
 {['cloze','fill_blank_options'].includes(d.type)&&<div className="editor-blanks"><p className="editor-list-label">Blank answers<small>{blankCount?`${blankCount} ${blankCount===1?'gap':'gaps'} in your prompt`:'Add ___ to your question to create a gap'}</small></p>{Array.from({length:blankCount},(_,i)=><label key={i}>Blank {i+1}<input value={lines('structured')[i]||''} onChange={e=>update('structured',i,e.target.value,blankCount)} placeholder="Correct word or phrase"/></label>)}</div>}
 {['short_answer','fill_blank','cloze'].includes(d.type)&&<details className="editor-details"><summary>Grading options</summary>{d.type!=='cloze'&&<label>Accepted alternative answers<textarea value={d.accepted||''} onChange={e=>field('accepted',e.target.value)} placeholder="One accepted answer per line"/></label>}<label className="editor-toggle"><input type="checkbox" checked={d.fuzzy!==false} onChange={e=>field('fuzzy',e.target.checked)}/><span>Accept minor typos<small>One-character typos in words of 5+ letters.</small></span></label></details>}
 {active===0&&<InlineImage label={d.type==='flashcard'?'Back image':'Answer image'} hint={d.type==='flashcard'?'Optional · shown on the back of the card':'Optional · shown after checking'} image={draft.answerImage} onPick={(file:File)=>upload(file,undefined,'answerImage')} onLink={(url:string)=>link(url,undefined,'answerImage')} onRemove={()=>shared('answerImage',undefined)} onView={setZoom} onEdit={()=>setEditImg({src:draft.answerImage,target:'answerImage'})}/>}
 </div></section>
 <section className="editor-section editor-step-panel" role="tabpanel" id="editor-panel-1" aria-labelledby="editor-tab-1" hidden={step!==1}><div className="editor-section-heading"><span><ImagePlus size={18}/></span><div><h2>Images</h2><p>Upload a file or paste a link. Large photos are resized automatically.</p></div></div><div className="editor-image-grid"><ImageUpload label={draft.type==='flashcard'?'Front image':'Question image'} hint="Shown above the question" image={draft.image} onPick={(file:File)=>upload(file)} onLink={(url:string)=>link(url)} onRemove={()=>shared('image',undefined)} onEdit={()=>setEditImg({src:draft.image,target:'image'})}/><ImageUpload label={draft.type==='flashcard'?'Back image':'Answer image'} hint={draft.type==='flashcard'?'Shown on the back of the card':'Shown after checking'} image={draft.answerImage} onPick={(file:File)=>upload(file,undefined,'answerImage')} onLink={(url:string)=>link(url,undefined,'answerImage')} onRemove={()=>shared('answerImage',undefined)} onEdit={()=>setEditImg({src:draft.answerImage,target:'answerImage'})}/></div>{choiceImages&&<div className="editor-choice-image-list"><p className="editor-list-label">{imageList.title}{allTypes.length>1?` · type ${active+1}`:''}<small>{(d.type==='matching'?pairs.some((p:string[])=>p[0].trim()||p[1].trim()):(d.type==='ordering'?steps:choices).some((x:string)=>x.trim()))?imageList.hint:`Add ${d.type==='matching'?'pairs':d.type==='ordering'?'steps':d.type==='fill_blank_options'?'words':'choices'} in step 1 first.`}</small></p>{d.type==='matching'?pairs.map((p:string[],i:number)=><div className="editor-choice-image-row is-pair" key={`${i}-${p[0]}`}>{imageButton(p[0],p[0]||`pair ${i+1} left`,()=>{const n=pictureLabel(i+1);structuredChange(i,n+'|'+p[1]);return n;})}<span>{p[0]||'Left side'} <i>↔</i> {p[1]||'Matching answer'}</span>{imageButton(p[1],p[1]||`pair ${i+1} right`,()=>{const n=pictureLabel(String.fromCharCode(65+i));structuredChange(i,p[0]+'|'+n);return n;})}</div>):(d.type==='ordering'?steps:choices).filter((x:string)=>x.trim()).map((x:string,i:number)=><div className="editor-choice-image-row" key={`${i}-${x}`}>{imageButton(x)}<span><b>{d.type==='single_choice'||d.type==='multi_select'?String.fromCharCode(65+i):i+1}</b> {x}</span><small>{d.optionImages?.[x.trim()]?'Image added':'No image'}</small></div>)}</div>}{mediaError&&step===1&&<p className="editor-media-error" role="alert">{mediaError}</p>}{mediaNote&&step===1&&<p className="editor-media-note" role="status">{mediaNote}</p>}</section>
 <section className="editor-section editor-ready editor-step-panel" role="tabpanel" id="editor-panel-2" aria-labelledby="editor-tab-2" hidden={step!==2}><div className="editor-section-heading"><span>03</span><div><h2>Optional settings</h2><p>You can save without adding anything here.</p></div></div><details className="editor-details editor-organization" open={!!(draft.subject||draft.topic||draft.tags)}><summary>Organize question <small>Subject, topic & tags</small></summary><div className="editor-meta-grid"><label>Subject<input value={draft.subject} onChange={e=>shared('subject',e.target.value)} placeholder="e.g. Geography"/></label><label>Topic<input value={draft.topic} onChange={e=>shared('topic',e.target.value)} placeholder="e.g. Capitals"/></label></div><label>Tags<input value={draft.tags||''} onChange={e=>shared('tags',e.target.value)} placeholder="e.g. revision, chapter 1"/><small>Separate tags with commas.</small></label></details><label className="editor-toggle"><input type="checkbox" checked={prepareAudio} onChange={e=>setPrepareAudio(e.target.checked)}/><span><Volume2 size={16}/>Prepare voice when saving<small>Makes the first playback instant.</small></span></label></section>
 </fieldset>
 {preview&&<section className="editor-live-preview" aria-label="Question preview"><div className="editor-live-preview-heading"><Eye size={16}/><strong>Preview{allTypes.length>1?` · type ${active+1}`:''}</strong><button type="button" aria-label="Close preview" onClick={()=>setPreview(false)}><X size={16}/></button></div><QuestionTypePreview key={active} draft={{...draft,...d,image:draft.image,answerImage:draft.answerImage}} choices={choices} pairs={pairs} steps={steps}/></section>}
 <ImageLightbox src={zoom} onClose={()=>setZoom(null)}/>
 {editImg&&<ImageEditor src={editImg.src} onCancel={closeEditor} onSave={(image:string)=>{place(image,editImg.key,editImg.target);setMediaNote('');closeEditor();}}/>}
 {status&&<p className="editor-save-message" id={statusId} role={busy?'status':'alert'} aria-live="polite">{busy&&<LoaderCircle size={17} className="speech-spinner"/>}{status}</p>}
 <footer className="question-editor-actions editor-tab-actions"><div className="editor-step-controls"><Button variant="outline" onClick={()=>step===0?onCancel():goStep(step-1)} disabled={busy}>{step===0?'Cancel':'Back'}</Button><Button variant="outline" onClick={()=>goStep(step+1)} disabled={busy||step===tabLabels.length-1}>Next</Button><Button variant="ghost" className="editor-preview-toggle" aria-pressed={preview} onClick={()=>setPreview(v=>!v)}>{preview?<EyeOff size={16}/>:<Eye size={16}/>}{preview?'Hide preview':'Preview'}</Button></div><Button onClick={onSave} disabled={busy}>{busy?<LoaderCircle size={16} className="speech-spinner"/>:<Save size={16}/>} {busy?'Saving…':editing?'Save changes':'Create question'}</Button></footer>
 </div>;
}
