import React,{useEffect,useRef,useState} from 'react';
import {Button} from './components/Button';
import {textGrade} from '../learning-core.js';
import {seededShuffle,isPictureLabel} from '../question-variants.js';
import {ZoomButton} from './ImageViewer';
export function ItemMedia({item,text}:any){const src=item.optionImages?.[text];return src?<img className="item-media" src={src} alt="" draggable={false}/>:null;}
export function ItemText({item,text,className}:any){return isPictureLabel(text)&&item.optionImages?.[text]?<span className="visually-hidden">{text}</span>:<span className={className}>{text}</span>;}
export function ItemZoom({item,text}:any){const src=item.optionImages?.[text];return src?<ZoomButton src={src} alt={text} label={`Enlarge picture for ${text}`}/>:null;}
const PAIR_COLOURS=['#2ec4a6','#facc15','#f06595','#38bdf8','#a3e635','#f97316'];
export function MatchingAnswer({item,value,onChange,disabled,onGrade}:any){
 const [active,setActive]=useState<number|null>(null),[message,setMessage]=useState(''),[lines,setLines]=useState<any[]>([]);
 const board=useRef<HTMLDivElement>(null),values=item.pairs.map((_,i)=>value[i]||''),rights=React.useMemo(()=>seededShuffle(item.pairs,item.id+(item.shuffleSeed||'')),[item]);
 useEffect(()=>{const el=board.current;if(!el)return;function measure(){const area=el!.getBoundingClientRect();setLines(values.flatMap((v,i)=>{if(!v)return [];const a=el!.querySelector(`[data-left="${i}"]`)?.getBoundingClientRect(),j=rights.findIndex(p=>p.right===v),b=el!.querySelector(`[data-right="${j}"]`)?.getBoundingClientRect();return a&&b?[{i,x1:a.right-area.left,y1:a.top+a.height/2-area.top,x2:b.left-area.left,y2:b.top+b.height/2-area.top}]:[];}));}measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect();},[item,value]);
 const drag=useRef<any>(null),skipClick=useRef(false),[draw,setDraw]=useState<any>(null);
 function link(left:number,right:string){onChange(values.map((v,i)=>i===left?right:v===right?'':v));setActive(null);setMessage('');}
 function connect(right:string){if(skipClick.current)return;if(active===null){const owner=values.indexOf(right);if(owner>=0)setActive(owner);else setMessage('Tap a word on the left first.');return;}link(active,right);}
 function anchor(el:Element,side:string){const area=board.current!.getBoundingClientRect(),r=el.getBoundingClientRect();return {x:(side==='left'?r.right:r.left)-area.left,y:r.top+r.height/2-area.top};}
 function hitAt(x:number,y:number,side:string){const el=document.elementFromPoint(x,y)?.closest(`[data-${side}]`) as HTMLElement|null;return el&&board.current?.contains(el)?el:null;}
 function down(e:React.PointerEvent){if(disabled||(e.pointerType==='mouse'&&e.button!==0))return;const el=(e.target as Element).closest('[data-left],[data-right]') as HTMLElement|null;if(!el)return;const side=el.hasAttribute('data-left')?'left':'right';drag.current={side,other:side==='left'?'right':'left',index:Number(el.dataset[side]),sx:e.clientX,sy:e.clientY,id:e.pointerId,moved:false,start:anchor(el,side)};}
 function move(e:React.PointerEvent){const d=drag.current;if(!d||d.id!==e.pointerId)return;if(!d.moved){if(Math.hypot(e.clientX-d.sx,e.clientY-d.sy)<8)return;d.moved=true;try{board.current!.setPointerCapture(e.pointerId);}catch{}setActive(null);setMessage('');}const area=board.current!.getBoundingClientRect(),hit=hitAt(e.clientX,e.clientY,d.other);setDraw({from:d.start,to:hit?anchor(hit,d.other):{x:e.clientX-area.left,y:e.clientY-area.top},side:d.side,index:d.index,hover:hit?Number(hit.dataset[d.other]):null});}
 function up(e:React.PointerEvent){const d=drag.current;if(!d||d.id!==e.pointerId)return;drag.current=null;setDraw(null);if(!d.moved)return;skipClick.current=true;setTimeout(()=>{skipClick.current=false;});const hit=hitAt(e.clientX,e.clientY,d.other);if(!hit)return;const j=Number(hit.dataset[d.other]);d.side==='left'?link(d.index,rights[j].right):link(j,rights[d.index].right);}
 function cancel(){drag.current=null;setDraw(null);}
 const curve=(a:any,b:any)=>`M ${a.x} ${a.y} C ${(a.x+b.x)/2} ${a.y}, ${(a.x+b.x)/2} ${b.y}, ${b.x} ${b.y}`;
 const drawing=(side:string,i:number)=>draw&&((draw.side===side&&draw.index===i)||(draw.side!==side&&draw.hover===i))?'true':undefined;
 const state=(i:number)=>disabled?(values[i]===item.pairs[i].right?'correct':'wrong'):active===i?'active':values[i]?'paired':'idle';
 const tint=(i:number)=>values[i]?{'--pair':PAIR_COLOURS[i%PAIR_COLOURS.length]} as React.CSSProperties:undefined;
 return <div className="structured-answer matching-answer"><p className="split-answer-help">{disabled?'Your matches':'Draw a line from each item to its match, or tap one and then the other.'}</p><div className="matching-board" ref={board} data-drawing={draw?'true':undefined} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel} onLostPointerCapture={e=>{if(e.target===e.currentTarget&&drag.current?.id===e.pointerId)cancel();}}><svg className="match-connections" aria-hidden="true">{lines.filter(l=>!draw||(draw.side==='left'?draw.index!==l.i:values[l.i]!==rights[draw.index].right)).map(l=><path key={l.i} data-state={state(l.i)} style={tint(l.i)} d={curve({x:l.x1,y:l.y1},{x:l.x2,y:l.y2})}/>)}</svg>{draw&&<svg className="match-drawing" aria-hidden="true"><path d={curve(draw.from,draw.to)}/><circle cx={draw.from.x} cy={draw.from.y} r="5"/><circle cx={draw.to.x} cy={draw.to.y} r={draw.hover===null?7:5}/></svg>}<div className="match-column" aria-label="Items to match">{item.pairs.map((p,i)=><div className="media-slot" key={p.left}><button data-left={i} data-state={state(i)} style={tint(i)} data-drawing={drawing('left',i)} aria-label={`Select ${p.left}`} aria-pressed={active===i} disabled={disabled} onClick={()=>{if(skipClick.current)return;setActive(i);setMessage('');}}><ItemMedia item={item} text={p.left}/><ItemText item={item} text={p.left}/>{values[i]&&<b>{i+1}</b>}</button><ItemZoom item={item} text={p.left}/></div>)}</div><div className="match-column" aria-label="Possible matches">{rights.map((p,j)=>{const owner=values.indexOf(p.right);return <div className="media-slot" key={p.right}><button data-right={j} data-state={owner<0?'idle':state(owner)} style={owner<0?undefined:tint(owner)} data-drawing={drawing('right',j)} aria-label={`Match with ${p.right}`} aria-pressed={owner>=0} disabled={disabled} onClick={()=>connect(p.right)}>{owner>=0&&<b>{owner+1}</b>}<ItemMedia item={item} text={p.right}/><ItemText item={item} text={p.right}/></button><ItemZoom item={item} text={p.right}/></div>;})}</div></div><div className="matching-tools"><p role="status">{message||`${values.filter(Boolean).length} of ${values.length} pairs connected`}</p>{!disabled&&<button onClick={()=>{onChange([]);setActive(null);setMessage('');}}>Reset matches</button>}</div>{!disabled&&<Button disabled={values.some(x=>!x)} onClick={()=>onGrade(values)}>Check matches</Button>}</div>;
}
export function InlineBlankAnswer({item,value,onChange,disabled,onGrade}:any){
 const multi=item.type==='cloze',values=multi?item.blanks.map((_,i)=>value[i]||''):[value||''];const parts=item.prompt.split(/_{2,}/g),complete=values.every(v=>v.trim());
 function field(index:number){const i=multi?index:0;return <input key={'blank-'+index} aria-label={`Blank ${index+1}`} autoComplete="off" spellCheck={false} value={values[i]} disabled={disabled} placeholder="" data-state={disabled?(textGrade({answer:multi?item.blanks[i]:item.answer,acceptedAnswers:multi?[]:item.acceptedAnswers,fuzzy:item.fuzzy},values[i])==='wrong'?'wrong':'correct'):'idle'} onChange={e=>{if(multi){const next=[...values];next[i]=e.target.value;onChange(next);}else onChange(e.target.value);}} onKeyDown={e=>{if(e.key==='Enter'&&complete&&!disabled)onGrade(multi?values:values[0]);}}/>;}
 return <div className="inline-blank-answer"><p className="blank-sentence">{parts.length>1?parts.map((part,i)=><React.Fragment key={i}>{part}{i<parts.length-1&&field(i)}</React.Fragment>):<>{item.prompt} {field(0)}</>}</p><p className="split-answer-help">Type directly into {multi?'each gap':'the gap'} to complete the sentence.</p>{!disabled&&<Button className="split-submit" disabled={!complete} onClick={()=>onGrade(multi?values:values[0])}>Check {multi?'answers':'answer'}</Button>}</div>;
}

export function WordBankAnswer({item,value,onChange,disabled,onGrade}:any){
 const [active,setActive]=useState(0),values=item.blanks.map((_,i)=>value[i]||''),parts=item.prompt.split(/_{2,}/g);
 function choose(option:string){const next=[...values];next[active]=option;onChange(next);const empty=next.findIndex((v,i)=>!v&&i>active);const first=next.findIndex(v=>!v);setActive(empty>=0?empty:first>=0?first:active);}
 return <div className="inline-blank-answer word-bank-answer"><p className="blank-sentence">{parts.map((part,i)=><React.Fragment key={i}>{part}{i<parts.length-1&&<button className="word-bank-gap" aria-label={`Blank ${i+1}: ${values[i]||'empty'}${!disabled&&active===i&&values[i]?', tap to clear':''}`} aria-pressed={active===i} disabled={disabled} data-filled={!!values[i]||undefined} data-state={disabled?(values[i]===item.blanks[i]?'correct':'wrong'):active===i?'active':'idle'} onClick={()=>{if(active===i&&values[i]){const next=[...values];next[i]='';onChange(next);}else setActive(i);}}>{disabled&&values[i]!==item.blanks[i]?<><s>{values[i]||'—'}</s> <b>{item.blanks[i]}</b></>:values[i]||<span className="word-bank-blank" aria-hidden="true"/>}</button>}</React.Fragment>)}</p><div className="word-bank-options" role="group" aria-label="Word bank">{item.options.map(option=><span className="media-slot" key={option}><button aria-label={`Option ${option}${values.includes(option)?', used':''}`} data-used={values.includes(option)||undefined} disabled={disabled} onClick={()=>choose(option)}><ItemMedia item={item} text={option}/><ItemText item={item} text={option}/></button><ItemZoom item={item} text={option}/></span>)}</div>{!disabled&&<div className="word-bank-tools"><span role="status">{values.filter(Boolean).length} of {values.length} gaps filled</span><button disabled={!values[active]} onClick={()=>{const next=[...values];next[active]='';onChange(next);}}>Clear selected gap</button></div>}{!disabled&&<Button className="split-submit" disabled={values.some(x=>!x)} onClick={()=>onGrade(values)}>Check answers</Button>}</div>;
}
